### ISSUE TITLE
Config params

### ISSUE THREAD

**Issue by addnab** [myoung34/docker-github-actions-runner#1]
Thank you for creating this repo.

I'd like to know how you figured out the argument field names here
https://github.com/myoung34/docker-github-actions-runner/blob/996106fdfc2c3b37e84cb09887b03f12776e3952/entrypoint.sh#L6

The documentation mentions `--url` and `--token` but not `--agent` and `--work`. All arguments passed to `./config.sh` looks like it's been passed to `Runner.Listener`. I'm having a hard time figuring out what this file is. Is there a way to decompile it?

**Comment by myoung34** [comment]
I'm not sure but it works. I think i found it on a random blog post (I'll be glad when all the official stuff gets better docs)
