### ISSUE TITLE
Deploying process works only once

### ISSUE THREAD

**Issue by timur265** [myoung34/docker-github-actions-runner#109]
Hi.

I set CI/CD on github and installed github-runner into docker container in server. The problem is the next when I deploy project in the first time everithing deploys properly and deploy has happened. However in the second time I meet this mistake

Setup SSH [2/2]

Install Deployer [1/2]
Command failed with exit code 1: ssh-agent -a /tmp/ssh-auth.sock [2/2]
Install Deployer [1/2]
Command failed with exit code 1: ssh-agent -a /tmp/ssh-auth.sock [2/2]
And to solve this problem I have to destroy my container and rebuild it again. But I just want to run docker and don't repeat creating-building container process

What can be the reason?

**Comment by myoung34** [comment]
there's not really enough information here for me to help you. Sockets are stateless here, so without the config and logs Im not sure what can be done from my side
