### ISSUE TITLE
Consider reusage of registered runner

### ISSUE THREAD

**Issue by NickVeld** [myoung34/docker-github-actions-runner#116]
Your approach assuming reregistering a runner each a restart of its container. But why just not try to save the artifacts of the registration in case of the problems

I suppose I can implement such the possibility

**Comment by myoung34** [comment]
I'm not against it but I'm not super interested in adding this myself

Runner registration takes only a few seconds, and runners are _generally_ meant to be long running (having none results in dropped actions)

I'm not sure I personally see the benefit, but I could see it being useful if it were added. I assume you'd just need to specify where the registration data lives so you can specify a volume (depending on which orchestrator is being used) but I'm not familiar with it.

**Comment by uwehdaub** [comment]
We explicitly decided against reusing any container state, because it created some problems in our setup.
As a result we are now using a runner for only one step and then delete the old one and start a new one.
(Off course we had to adapt the entrypoint slightly.)

If this would be implemented, we need a possibility to opt-out.

**Comment by NickVeld** [comment]
> 
> 
> We explicitly decided against reusing any container state, because it created some problems in our setup.
> As a result we are now using a runner for only one step and then delete the old one and start a new one.
> (Off course we had to adapt the entrypoint slightly.)
> 
> If this would be implemented, we need a possibility to opt-out.

Thanks. "Opt-out" is a quite simple: do not mount a directory and a state will stay inside.

**Comment by myoung34** [comment]
resolved by #117
