### ISSUE TITLE
Add Debian Buster

### ISSUE THREAD

**Issue by JulianGro** [myoung34/docker-github-actions-runner#118]
I am looking to run an arm64 Debian Buster runner. I would add Debian Buster myself, but I have very little idea how all of this stuff actually works.

I assume you get some kind of OS image and then provide Docker scripts to tell Docker what to do with that image, then upload the whole thing to hub.docker.com and then you can use the hosted base image to generate the runner from?

**Comment by myoung34** [comment]
The scripts to do this are in .GitHub/workflows

If you start a pr I'm happy to help and merge but I probably won't start that effort myself

**Comment by JulianGro** [comment]
Oh I think I understand how this works now. I will try myself on a PR.

**Comment by JulianGro** [comment]
Added in https://github.com/myoung34/docker-github-actions-runner/pull/119

**Comment by Niek** [comment]
It works great, thanks! Just one small warning I see in my scripts with lots of commands:
```
bash: warning: setlocale: LC_ALL: cannot change locale (en_US.UTF-8)
```
So maybe that should be added to the Dockerfile, something like this:
```docker
RUN echo "en_US.UTF-8 UTF-8" >> /etc/locale.gen && dpkg-reconfigure locales
```
