### ISSUE TITLE
Why is git built from source in Dockerfile.base?

### ISSUE THREAD

**Issue by joeyparrish** [myoung34/docker-github-actions-runner#125]
Why is git built from source in Dockerfile.base?

It would seem to me that we could build the image more quickly by installing git through apt.  On my arm64 device (Nvidia Jetson Nano 2GB), the git build is painfully slow.

Is the packaged version of git in Ubuntu focal too old or missing some critical feature?

Would you accept a PR to install git via "apt" instead?

Thanks for your time!

**Comment by myoung34** [comment]
At the time apt contained a much older version of git. 2.29.0 was the minimum version that would work on runners of any kind. If the version in apt for both debian and ubuntu are above that version ill accept a PR that rips it out

* https://github.com/actions/virtual-environments/blob/releases/ubuntu20/20210803/images/linux/Ubuntu2004-README.md
* https://github.com/actions/virtual-environments/blob/releases/ubuntu18/20210803/images/linux/Ubuntu1804-README.md

**Comment by joeyparrish** [comment]
Ah, I see.  It's 2.25 in focal.  How about I send a PR to add a comment that keeps well-meaning people like myself from "helping"?  :grin:

I did some digging and found that the minimum version of Ubuntu that would allow you to stop building git from source is "hirsute" (21.04).

**Comment by joeyparrish** [comment]
I found yet another solution.  If you're willing to use this official git-core PPA, we can pull a package from that: https://launchpad.net/~git-core/+archive/ubuntu/ppa

**Comment by joeyparrish** [comment]
I put together a PR for each approach:
  - #127 adds a comment about why git is built from source
  - #126 switches to using the git-core PPA to avoid building from source (and also adds a hefty comment)

Please let me know what you think!  My preference is the PPA solution (#127), but if you disagree, can we at least merge #126 to add the sort of comment that would have stopped me from trying to "fix" it?

Thanks!
