### ISSUE TITLE
Dockerfile.base fails to build on arm

### ISSUE THREAD

**Issue by joeyparrish** [myoung34/docker-github-actions-runner#128]
Dockerfile.base has a provision to skip installation of docker-compose on arm.  However, it then unconditionally tries to chmod that file:

https://github.com/myoung34/docker-github-actions-runner/blob/29cbe17895816370a7d5ff1275fb81514d6a8cb8/Dockerfile.base#L58-L59

On my arm64 device (Nvidia Jetson Nano), the image therefore fails to build.

We could make the chmod part of the previous command with curl, or make it conditional on the file existing first, but I have another solution to offer.

I have found that upgrading pip and then using pip to install docker-compose works well on all platforms.

I will have a PR for this shortly.  Let me know what you think!

**Comment by myoung34** [comment]
I'm OK with just removing docker-compose altogether (considering docker does not work yet upstream)

via pip has some other side effects.
I am curious what you mean by "breaks on arm64". There's a provision [here](https://github.com/myoung34/docker-github-actions-runner/blob/master/.github/workflows/base.yml#L37) that works with arm64 on Dockerfile.base

**Comment by joeyparrish** [comment]
What I mean is the line `chmod +x /usr/local/bin/docker-compose` fails when the previous line detects arm and skips installation of docker-compose.

I would also be fine to remove docker-compose from the image, since I don't personally use it in my workflows.  But I put some effort in to making it work, on the assumption that other people must use it if you provide it and there's a caveat about it in the README.

I can also offer to fix the `chmod` line in Dockerfile.base to test for existence first.

What's your preference?

**Comment by myoung34** [comment]
two options (no preference, except the latter one is less long)

```
  && [[ $(lscpu -J | jq -r '.lscpu[] | select(.field == "Vendor ID:") | .data') == "ARM" ]] && echo "Not installing docker-compose. See https://github.com/docker/compose/issues/6831" || ( curl -sL "https://github.com/docker/compose/releases/download/${DOCKER_COMPOSE_VERSION}/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose && chmod +x /usr/local/bin/docker-compose ) \
```

```
  && [[ $(lscpu -J | jq -r '.lscpu[] | select(.field == "Vendor ID:") | .data') == "ARM" ]] && echo "Not installing docker-compose. See https://github.com/docker/compose/issues/6831" || ( curl -sL "https://github.com/docker/compose/releases/download/${DOCKER_COMPOSE_VERSION}/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose ) \
  && [[ -f "/usr/local/bin/docker-compose" ]] && chmod +x /usr/local/bin/docker-compose \

```

**Comment by myoung34** [comment]
or a third option: rip out docker-compose

I dont think it can work without docker working

**Comment by joeyparrish** [comment]
I think the second option there has a small bug.  If [[ -f ... ]] fails, the rest of the commands after chmod will stop, right?

I've tested the first option and I'm happy with it if you are.  I'll send another PR.

**Comment by myoung34** [comment]
thats fine. yeah youre right, the 2nd one would need to be `&& [[ -f "/usr/local/bin/docker-compose" ]] && chmod +x /usr/local/bin/docker-compose || : \` but i think i prefer the former and not this way

**Comment by joeyparrish** [comment]
Thanks for working through these issues with me.  I really appreciate it!
