### ISSUE TITLE
Ephemeral mode

### ISSUE THREAD

**Issue by joeyparrish** [myoung34/docker-github-actions-runner#137]
Any interest in an "ephemeral mode"?  I've been working on this for my own purposes, but if you're interested, I'll send a PR instead of maintaining an indefinite fork.

The idea is to launch an alternative script (overriding CMD in Dockerfile).  Instead of `/actions-runner/bin/runsvc.sh`, this script would run `/actions-runner/run.sh --once`, with special handling to re-launch after software updates.

When the job is finished, the container terminates.  This is then wrapped in a system service that starts a fresh container, giving us an ephemeral, self-hosted runner, more like what you expect from GitHub's own runner VMs.

**Comment by myoung34** [comment]
Id be curious to see it, but ideally id rather the runner team resolve https://github.com/actions/runner/issues/246 for a lot of reasons instead of adding that complexity here

**Comment by joeyparrish** [comment]
I completely agree.  Upstream support would be better.

I'll create the PR anyway.  I think you'll find it's not too bad.  Less than 40 lines of bash, just one script, no other changes.
