### ISSUE TITLE
Is there a way to change the default locale

### ISSUE THREAD

**Issue by geoffreyIOOF** [myoung34/docker-github-actions-runner#138]
Hi,
I can't find a way to change the default locale from en_US to en_AU

Any advice on this ?

Cheers

**Comment by myoung34** [comment]
This isnt something ive tried. In theory you could add it to the CMD? Im not sure to be honest

**Comment by pabloromeo** [comment]
Is that the locale on your physical host?
If so you could try mapping the host's locale as a volume:
```
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
```

**Comment by geoffreyIOOF** [comment]
Thanks I ll try that.
