### ISSUE TITLE
Debian Sid failing

### ISSUE THREAD

**Issue by JulianGro** [myoung34/docker-github-actions-runner#142]
GitHub Actions Sid builds are failing because Sid is apparently not on their repository (anymore?) https://download.docker.com/linux/debian/dists/
I said that I had Sid running in https://github.com/myoung34/docker-github-actions-runner/pull/123#pullrequestreview-711525427 so I cannot imagine it not working before. Maybe they stopped providing Sid packages because no one in their right mind would use Docker on Sid?

Here is a GHA failing on Sid https://github.com/myoung34/docker-github-actions-runner/runs/3569202962?check_suite_focus=true

**Comment by myoung34** [comment]
👁️ 👁️ 

This is a strange failure. Ill dig in tomorrow unless you post updates here.

**Comment by JulianGro** [comment]
I will do a little update to the readme, because Debian Bullseye is stable now, but leave this issue out for now.
Personally I have no interest on ever using Sid in Docker. There isn't even a package on Dockers repository for Debian Bookworm, which is current Testing, yet.

**Comment by JulianGro** [comment]
@myoung34 I know why this worked in the past now.
This is from the last working Debian Sid run:
```
#21 4.674 --------OS Information--------
#21 4.677 PRETTY_NAME="Debian GNU/Linux 11 (bullseye)"
#21 4.677 NAME="Debian GNU/Linux"
#21 4.677 VERSION_ID="11"
#21 4.677 VERSION="11 (bullseye)"
#21 4.677 VERSION_CODENAME=bullseye
#21 4.677 ID=debian
#21 4.677 HOME_URL="https://www.debian.org/"
#21 4.677 SUPPORT_URL="https://www.debian.org/support"
#21 4.677 BUG_REPORT_URL="https://bugs.debian.org/"
#21 4.678 ------------------------------
#21 4.678 The current OS is Debian based
#21 4.678 --------Debian Version--------
#21 4.680 11.0
#21 4.681 ------------------------------
#21 4.681 /usr/bin/apt-get
#21 4.840 Get:1 https://download.docker.com/linux/debian bullseye InRelease [43.3 kB]
#21 4.880 Get:2 http://deb.debian.org/debian sid InRelease [165 kB]
#21 5.110 Get:3 https://download.docker.com/linux/debian bullseye/stable amd64 Packages [4475 B]
#21 5.361 Get:4 http://deb.debian.org/debian sid/main amd64 Packages [8763 kB]
```

The system called itself "bullseye" because Sid is unstable and isn't supposed to ever be directly used. Back then, Bullseye was  still Testing and the Debian team probably just never bothered to change the name inside Sid. Until Bookworm became the new Testing with the release of Debian Bullseye as Stable.
It looks like the system now properly identifies as "sid":
```
#18 4.627 --------OS Information--------
#18 4.629 PRETTY_NAME="Debian GNU/Linux bookworm/sid"
#18 4.629 NAME="Debian GNU/Linux"
#18 4.629 ID=debian
#18 4.629 HOME_URL="https://www.debian.org/"
#18 4.629 SUPPORT_URL="https://www.debian.org/support"
#18 4.629 BUG_REPORT_URL="https://bugs.debian.org/"
#18 4.630 ------------------------------
#18 4.630 The current OS is Debian based
#18 4.630 --------Debian Version--------
#18 4.639 bookworm/sid
#18 4.640 ------------------------------
```

I guess the way to work around this for now is to use the Docker bullseye repo on Sid. 
Maybe @Niek wants to take a look, as they are probably the only person actually using this?

**Comment by joeyparrish** [comment]
Does anybody actually need an image based on Sid?  Could it just be deprecated on Docker Hub and removed from the workflow?

**Comment by myoung34** [comment]
If I dont hear back by Friday I'll deprecate it

**Comment by Niek** [comment]
For my use-case, Sid is pretty important. I will open a PR to fix this.

PR: https://github.com/myoung34/docker-github-actions-runner/pull/145
