### ISSUE TITLE
Issues running software inside container

### ISSUE THREAD

**Issue by JulianGro** [myoung34/docker-github-actions-runner#144]
I am having issues where software that works fine outside the Docker container doesn't work inside it.
In my case vcpkg is freezing when trying to check the "compiler hash".
It is also eternally waiting for something when trying to actually build something:
```
Starting package 1/5: glslang:arm64-linux-release
Building package glslang[core]:arm64-linux-release...
read(4, "-- Extracting source /tmp/github"..., 4096) = 165
read(4, "-- Using source at /tmp/github-r"..., 4096) = 146
read(4, "-- Configuring arm64-linux-relea"..., 4096) = 39
read(4, 0x55af51c0b0, 4096)             = ? ERESTARTSYS (To be restarted if SA_RESTART is set)
--- SIGURG {si_signo=SIGURG, si_code=SI_USER, si_pid=1, si_uid=0} ---
read(4, 0x55af51c0b0, 4096)             = ? ERESTARTSYS (To be restarted if SA_RESTART is set)
--- SIGURG {si_signo=SIGURG, si_code=SI_USER, si_pid=1, si_uid=0} ---
read(4, 0x55af51c0b0, 4096)             = ? ERESTARTSYS (To be restarted if SA_RESTART is set)
--- SIGURG {si_signo=SIGURG, si_code=SI_USER, si_pid=1, si_uid=0} ---
```
Both the host system and the container are Debian Bullseye aarch64. Running directly on the host system works fine.

**Comment by myoung34** [comment]
to be honest I wouldn't even know where to begin to troubleshoot this on my side

**Comment by JulianGro** [comment]
How do you think I feel :+1: 
I am trying the Ubuntu image right now, just to check that. Other than that I was hoping someone else might have run into issues like that with Docker and could point me into the right direction.

**Comment by JulianGro** [comment]
Well I tried the Ubuntu image and I tried the official Debian image (without github actions) and ran into the same problems.
Upgrading cmake doesn't help either.
I guess it must be some problem with vcpkg + docker or cmake + docker..

Whatever it is, it doesn't have anything to do with these images or the github actions software in them.

**Comment by JulianGro** [comment]
My vcpkg package was missing a hidden file... obviously since it was hidden, I never noticed that it was missing.
