### ISSUE TITLE
Support new --ephemeral flag in runner v2.282.0

### ISSUE THREAD

**Issue by joeyparrish** [myoung34/docker-github-actions-runner#148]
I should have waited a bit, perhaps, to use the official `--ephemeral` flag, since its introduction also deprecates the `--once` flag I just added support for in PR #140.  But now that the new [v2.282.0](https://github.com/actions/runner/releases/tag/v2.282.0) release is out with `--ephemeral`, we should migrate to that.

Unfortunately, `--once` could be sent to `run.sh`, whereas `--ephemeral` must be given to `config.sh`.  This will require changes to the entrypoint, and perhaps a new config variable.

I'll start making changes accordingly, and send a PR soon.

**Comment by myoung34** [comment]
Glad youre keeping up with the upstream changeset better than me 😆

**Comment by uwehdaub** [comment]
Hi @joeyparrish 
did you found some time to work on this?
I'm asking, because I have to decide, whether to wait for this change or start working on implementing it.

BR

**Comment by joeyparrish** [comment]
I did work on this some, but I got pulled onto other things and never finished the work.  Let me check what state I left it in.  Perhaps I can push my work in progress to a branch and you can decide whether you want to start from there or start over.

**Comment by myoung34** [comment]
@joeyparrish if you can push it up with some notes inside about your thinking/thoughts im happy to take it over. All i really need is a rough scaffold and some of your thoughts tbh.

**Comment by joeyparrish** [comment]
Looks like I hadn't gotten anything useful done.  I won't be upset if someone else does the work.

I think all the information I have is in the original issue post at the top of this thread.  My thought was to add a new environment variable for ephemeral mode, since `--ephemeral` has to be given to `config.sh`.  Then `--once` can be removed from `ephemeral_runner.sh`.  The rest of what that script does may still be needed, though.

What would be very nice is if the new environment variable could override the default CMD, so that all one has to do is set that variable.  Then overriding CMD as described in README is not needed.
