### ISSUE TITLE
Cross plattform builds?

### ISSUE THREAD

**Issue by jschlyter** [myoung34/docker-github-actions-runner#153]
Would it be possible to publish the arm containers under specific name so one can use them cross-plattform?

E.g., the official debian arm32v7 image is published at `docker.io/arm32v7/debian:stretch` which makes it easy to run under qemu-arm-static on Fedora amd64.

**Comment by myoung34** [comment]
I'm not sure I follow. Everything is already cross platform and documented on how to find. I also wouldn't have permission to push to those accounts.

Most people look under the official repo for the container, not an arm32v7 maintainer

**Comment by jschlyter** [comment]
Thanks! It seems it works differently when using multi-arch images (like this one). For the record, one would use something like`docker run -it --rm --arch arm myoung34/github-runner:ubuntu-bionic` to run foreign architectures (e.g. arm on x86).

**Comment by myoung34** [comment]
what do you mean "works differently"

**Comment by jschlyter** [comment]
> what do you mean "works differently"

Without multi-arch, the arch is implicit by the image and does not need to be specified - e.g., when using the official arm32v7 image on x86 one can simple pull and execute.

**Comment by myoung34** [comment]
if you wanted to submit a PR to add additional tags during deployment that would be fine, but id like to not overly clutter the workflows


Im still having a hard time understanding though

Theres no difference between `docker run -it --rm --platform=linux/arm/v7 myoung34/github-runner:ubuntu-bionic` and  `docker run -it --rm arm32v7/github-runner:ubuntu-bionic`  except that im lost as a maintainer on the latter one, making it hard for people to see where to submit issues. Also: 

* i'd need permission to update the README in `n` places where n is the number of dockerhub users that im not (README is manual on docker hub)
* I'd need `n` tokens for dockerhub to push to `n` repos
* people would have a hard time knowing who the maintainer is for help, having to find it and potentially submit it in the wrong place
* i'd lose statistics for other builds
* without qemu no one runs cross builds anyway. IE whats the gain for running ARM builds of the exact same dockerfile on an x86_64 cpu?

"works differently" would in fact be more prevalent by having it pushed elsewhere.
AFAICT it works the same just broken for obvious reasons when the wrong arch is specified:

```
$ docker run -it --rm --platform=linux/arm/v7 myoung34/github-runner:ubuntu-bionic
standard_init_linux.go:219: exec user process caused: exec format error
```

**Comment by jschlyter** [comment]
We are in agreement, there's nothing more do be done here as far as a can see - it's just a matter how one launch the containers. Nothing to see, carry on and keep up the good work!

**Comment by myoung34** [comment]
Thanks! If you see any improvements in terms of clarity or usage feel free to submit a PR
