### ISSUE TITLE
GitHub Sponsoring

### ISSUE THREAD

**Issue by wgehring** [myoung34/docker-github-actions-runner#157]
Hello @myoung34,
I am writing to you on behalf of Daimler / Mercedes-Benz AG. We would like to sponsor you, and I have sent you an email to this end last week (7c8cty1esv2n@opayq.net). Did you receive it and had a chance to take a look?
Cheers
 Wolfgang

**Comment by myoung34** [comment]
@wgehring Sorry I was at KubeCon. I saw it and will take a look/reply via email.

Thanks!
