### ISSUE TITLE
issues using custom docker image based on AL2

### ISSUE THREAD

**Issue by yrsurya** [myoung34/docker-github-actions-runner#158]
I am able to use previous version successfully but when I am trying to update to latest version seeing following issue

--------OS Information--------
NAME="Amazon Linux"
VERSION="2"
ID="amzn"
ID_LIKE="centos rhel fedora"
VERSION_ID="2"
PRETTY_NAME="Amazon Linux 2"
ANSI_COLOR="0;33"
CPE_NAME="cpe:2.3:o:amazon:amazon_linux:2"
HOME_URL="https://amazonlinux.com/"
------------------------------
"centos rhel fedora"
Can't detect current OS type based on /etc/os-release.
Can't install dotnet core dependencies.
You can manually install all required dependencies based on following documentation
https://docs.microsoft.com/en-us/dotnet/core/linux-prerequisites?tabs=netcore2x
The command '/bin/bash -o pipefail -c chmod +x /actions-runner/install_actions.sh   && /actions-runner/install_actions.sh ${GH_RUNNER_VERSION} ${TARGETPLATFORM}   && rm /actions-runner/install_actions.sh' returned a non-zero code: 1

**Comment by myoung34** [comment]
How are you running this?

 I dont build any RHEL compatible docker images.

**Comment by myoung34** [comment]
Without more context (including the Dockerfile and scripts) there's nothing I can do here unfortunately. I don't provide any RHEL based images 

If you'd like to submit a working one as a PR I'm happy to help merge it though.
