### ISSUE TITLE
ssl certificate problem

### ISSUE THREAD

**Issue by duxbuse** [myoung34/docker-github-actions-runner#160]
My organisations uses a self signed cert which curl takes issue with. Would be nice to have a way to accept self signed certs

**Comment by myoung34** [comment]
which curl? Theres not enough info here to really be of help

**Comment by duxbuse** [comment]
Sorry I meant during this call
https://github.com/myoung34/docker-github-actions-runner/blob/569fdcef4245dd00e1117bc033ef979df362bf18/token.sh#L36

To access the https endpoint for my orgs GHE requires using my orgs self signed cert.

So my options are to add `-k` to your script (not the good option)
Or use your image as a base load in my orgs certs and run `update-ca-certs`

I guess I'm wondering if there is a better way to get the certs working without having to rebuild the image.

**Comment by myoung34** [comment]
For security sake I wouldn't let all the curl's do insecure mode.

Your best bet is to fork it and add the cert to the chain for this scenario

Unfortunately not every unique case can avoid custom builds
