### ISSUE TITLE
Unable to use snapcraft

### ISSUE THREAD

**Issue by AllinolCP** [myoung34/docker-github-actions-runner#166]
Hi, Is there any way to install snapcraft into the image?

Thank you

**Comment by myoung34** [comment]
Its not in the official runner [here](https://github.com/actions/virtual-environments/blob/main/images/linux/Ubuntu2004-Readme.md) so I wouldn't put it in the base here

There's already concern about size [from others](https://github.com/myoung34/docker-github-actions-runner/issues/163) so I would avoid anything not in the official set up.
