### ISSUE TITLE
git complains over missing /usr/etc dir

### ISSUE THREAD

**Issue by davidkarlsen** [myoung34/docker-github-actions-runner#169]
Some git operations complain over a missing `/usr/etc` directory, why not just run the precompiled ppa's from https://launchpad.net/~git-core/+archive/ubuntu/ppa ?

CC @otterian

**Comment by myoung34** [comment]
Im not against the PPA if you know how to shim it into the `Dockerfile.base`

At the time there was nothing above 2.19 available, and 2.29+ was needed (and 2.25 is still in apt as-is)
whatever solution chosen should also work for Debian
