### ISSUE TITLE
Kubernetes Deployment overwriting MountPath

### ISSUE THREAD

**Issue by jensenity** [myoung34/docker-github-actions-runner#173]
Hi, So im using the kubernetes template you shared on the README but when same github runners are on the same node, due to the mountpath, it overwrites each other and because of that, runners that shares the same node and same mountpath fails in the middle of my action. Can you share how I can create a workaround with this issue?

Do I have to use StatefulSet?

**Comment by myoung34** [comment]
You have to create a unique mount path per runner if you need to mount a directory

See here for usage on that https://github.com/myoung34/docker-github-actions-runner/issues/167

**Comment by jensenity** [comment]
Thank you very much!
