### ISSUE TITLE
Docker not found in armv7 images

### ISSUE THREAD

**Issue by pabloromeo** [myoung34/docker-github-actions-runner#175]
Up until recently I was able to run `docker stack deploy` commands without problems (mounting `/var/run/docker.sock` on the runner). 
However, after updating to the latest `ubuntu-bionic` image, docker no longer appears to be installed and builds fail due to:
```
docker: command not found
```
I've ssh'ed into the runner container and indeed it appears that docker is not installed or not in the path.
![image](https://user-images.githubusercontent.com/41338020/150478728-626d324e-a069-42cd-9c00-708de5c496fc.png)

Has the setup changed recently in regards to calling docker commands on the host?

FYI: I just reverted back to `2.286.1-ubuntu-bionic` and it's working again, so there's something different in `ubuntu-bionic` it seems.

**Comment by myoung34** [comment]
Ill take a look. I did some refactoring and something might have slipped through

**Comment by myoung34** [comment]
@pabloromeo I dont have an arm v7 handy

Can you see if git and docker are working for me in:

* latest (ubuntu eoan `docker pull myoung34/github-runner:latest`)
* ubuntu bionic (`myoung34/github-runner:ubuntu-bionic`
* debian sid (`myoung34/github-runner:debian-sid`)
* debian bullseye (`myoung34/github-runner:debian-bullseye`)

by running `git --version` and `which -a docker`

**Comment by myoung34** [comment]
I just ran some tests

* amd64 seems fine, all 4 have docker `20.10.12` and git `2.34.1`
* arm64 seems to also be missing docker and git for ubuntu bionic and debian bullseye. the other 2 show docker `20.10.12` and git `2.34.1`
* armv7 is probably in the same boat as arm64 if you can confirm that would help tremendously

**Comment by myoung34** [comment]
This might be resolved with https://github.com/myoung34/docker-github-actions-runner/commit/8810c62144187d38e6aa759c90d86127f534a9ef 
if you can retest

I confirmed that git and docker are fixed in arm64

**Comment by pabloromeo** [comment]
Hi!
Yeah, I was about to test the tags you mentioned above. Sure, I'll give it a shot right now.

**Comment by pabloromeo** [comment]
Stuff seems to be working now with the latest pushed versions:
I've tried both `latest` and `ubuntu-bionic` and both now have git version 2.33.1 and docker 20.10.12. 
So that last PR seems to have fixed it :)

**Comment by myoung34** [comment]
Awesome thanks for verifying

**Comment by pabloromeo** [comment]
Sure thing, glad to help!

**Comment by pabloromeo** [comment]
This seems to be happenning again :( were there new changes that might have broken the install of docker? I'm getting command not found again.

**Comment by myoung34** [comment]
I dont see any errors in the latest builds, Ill dig in and see if i can confirm

**Comment by pabloromeo** [comment]
`ubuntu-bionic` is the tag I'm running

**Comment by myoung34** [comment]
I just tested this on arm64:

```myoung@cluster13:~$ sudo docker run -it --entrypoint /bin/bash myoung34/github-runner:ubuntu-bionic
root@2edcc95635ea:/actions-runner# git --version
git version 2.35.0
root@2edcc95635ea:/actions-runner# docker --version
Docker version 20.10.12, build e91ed57
root@2edcc95635ea:/actions-runner#``` I dont see any errors in the build log, but I dont have an armv7 to test with. ubuntu-bionic seems fine for allt he other architectures i can test (amd64)

**Comment by pabloromeo** [comment]
One way i've tried exploring the contents of the image is using [dive](https://github.com/wagoodman/dive) against the armv7 digest for `ubuntu-bionic`:

```
dive myoung34/github-runner@sha256:276dd93eb6cf27cc2cba8fcf3058a3d9c9a2c520ded0450719978b580adc52e8
```

I'm not seeing /usr/bin/docker in there:
![image](https://user-images.githubusercontent.com/41338020/151668929-094d1c1d-6140-4091-a4e1-a013e36b15ff.png)


However, I do see it if I view the layers for other architectures of that same tag (amd64):
![image](https://user-images.githubusercontent.com/41338020/151668872-58593dda-26ce-4c7b-959e-e9100bf5f82d.png)

**Comment by myoung34** [comment]
I got my hands on a raspberry pi 2 with armv7 so ill be looking into this soon

**Comment by pabloromeo** [comment]
Awesome! Let me know if there's anything I can test from here. I run it on rpi 4.

**Comment by myoung34** [comment]
@pabloromeo how are you running armv7 on a raspberry pi 4?
Feel free to chat me on keybase if its easier than here 🤔

**Comment by pabloromeo** [comment]
Ah I'm not running the 64bit version of the OS, I've had this cluster running for ages and I've been too lazy to rebuild it.
