### ISSUE TITLE
Docker in Docker?

### ISSUE THREAD

**Issue by ScottPierce** [myoung34/docker-github-actions-runner#176]
I've been using your docker image for a long time. Thank you!

I just noticed in the documentation, and had a few questions:
```
    volumes:
      - '/var/run/docker.sock:/var/run/docker.sock'
      - '/tmp/runner:/tmp/runner'
      # note: a quirk of docker-in-docker is that this path
      # needs to be the same path on host and inside the container,
      # docker mgmt cmds run outside of docker but expect the paths from within
```

1. I was under the impression that using github containers wasn't possible when using a runner inside of docker. Is that no longer true?
2. I'm currently running 10 runners on a single machine. Is it safe to change this directly to something besides `/tmp/runner`, so that each runner is unique?
3. I'm currently running my runners on a Windows machine. There is (significantly?) decreased disk performance by exposing the directory to the host windows OS. Currently I'm just creating volumes and letting docker maintain them. Is there a way for me to get docker-in-docker working using this approach, or do I need to expose the path to the host OS?

**Comment by myoung34** [comment]
1. Docker in docker is still mostly unsupported. Notes [here](https://github.com/myoung34/docker-github-actions-runner#docker-support)
2. Thats a safe assumption . if youre not trying to persist data you dont need to specify it at all
3. Thats an unknown scenario to me. I havent tested windows as a host at all, so I'm unsure. If youre not persisting data you dont need to expose the directory or the socket

**Comment by myoung34** [comment]
If theres anything else feel free to re-open

**Comment by ScottPierce** [comment]
@myoung34 If I don't persist data, will updates work?

**Comment by myoung34** [comment]
They work without persisting data if you use `latest` and always pull or if you update your tags to use whatever the newest tag is

Otherwise: no
