### ISSUE TITLE
disable auto-update

### ISSUE THREAD

**Issue by davidkarlsen** [myoung34/docker-github-actions-runner#181]
https://github.com/actions/runner/releases/tag/v2.287.1 provides the option to disable auto-update, which stops the pod from crashing. Maybe run with this option?

CC @otterian

**Comment by myoung34** [comment]
Nice! Ive been waiting on this.

Ill run some tests over the next few days

**Comment by jcyriac-synamedia** [comment]
we were also waiting for this feature. our runners have been crashing from time to time due to the auto-upgrade. we built our wrapper around this docker image and we couldn't use `latest` always. 

`disable auto-update` option will be highly appreciated. thanks

**Comment by harsha-syna** [comment]
Great guys we are waiting for this.

**Comment by myoung34** [comment]
This is now in from #184 
Check out the readme, but just add `DISABLE_AUTO_UPDATE` env var with any value to get the new behavior
