### ISSUE TITLE
Agent restart

### ISSUE THREAD

**Issue by mvbelik** [myoung34/docker-github-actions-runner#185]
Good afternoon, the agent is trying to update and restarts in a circle

Cannot configure the runner because it is already configured. To reconfigure the runner, run 'config.cmd remove' or './config.sh remove' first.

√ Connected to GitHub

Current runner version: '2.286.1'
2022-02-04 05:38:44Z: Listening for Jobs
Runner update in progress, do not shutdown runner.
Downloading 2.287.1 runner
Waiting for current job finish running.
Generate and execute update script.
Runner will exit shortly for update, should be back online within 10 seconds.
Runner update process finished.
Runner reusage is disabled
Configuring

**Comment by erik-nordic** [comment]
This should have been fixed in https://github.com/myoung34/docker-github-actions-runner/pull/184

this merged yesterday, so you might have missed it so far :)
