### ISSUE TITLE
Change UID/GUID in the runner image

### ISSUE THREAD

**Issue by Otterian** [myoung34/docker-github-actions-runner#186]
Hi,

Thank you for your time and continuing commitment to this project.

Ideally the user in the image should run as UID 1001 and GID 121, as it does in the official runners from GitHub. This in order to be as identical as possible to the official runners, and prevent possible issues with Actions that may be depending on these variables.

We've done this in our downstream derivative of the Ubuntu image: https://github.com/evryfs/github-actions-runner/blob/test-NewImage/Dockerfile#L23-L24 - and it'd be great if it is done here as well. In addition to the mentioned reasons for doing this - dropping root in images is good security practice in general - even _if_ downstream images drop root.

I'd be happy to create a PR for this if you want this implemented. :+1:

Please let me know if anything is unclear, or if you have other thoughts about this :smile:

**Comment by myoung34** [comment]
If you can scaffold something I can see the value in adding it for sure

**Comment by Skyxim** [comment]
For example, when compiling OpenWRT, using root will be warned

**Comment by myoung34** [comment]
resolved by #223 

See [the usage docs here](https://github.com/myoung34/docker-github-actions-runner/wiki/Usage#non-root-runners)
