### ISSUE TITLE
Github runner auto-update no longer works

### ISSUE THREAD

**Issue by juhhov** [myoung34/docker-github-actions-runner#187]
Depending on docker daemon type and failure options github runner internal update leads to either container being recreated or eventually update loop. Github runner version doesn't update in either of these scenarios.
For a long time we used myoung34@2.277.1 image and it used to survice auto-updates just fine. After update to myoung34@2.286.0 this issue raised. I am suspecting https://github.com/myoung34/docker-github-actions-runner/pull/149 broke the auto-update.

Adding `command: "/actions-runner/bin/runsvc.sh"` to stack seems to resolve the issue, but it would be better if default command/entrypoint was enough.

**Comment by myoung34** [comment]
im not sure I follow, but you can override command at runtime if you want to change it to `/actions-runner/bin/runsvc.sh`

I wont revert #149 however as that solves a lot of the trap issues and you can still override CMD [here](https://github.com/myoung34/docker-github-actions-runner/blob/master/entrypoint.sh#L122)

**Comment by juhhov** [comment]
Yep, changing the command resolves the issue. My question however is should the image be able to handle auto-update with default command? Most likely all users will stumble into this problem unless they disable auto-update.

**Comment by myoung34** [comment]
I'd rather the default handle the signals correctly and avoid all the wrappers and have auto updates be the side effect since most container use cases can't handle updates restarting the container

**Comment by myoung34** [comment]
Thanks however, I might add a snippet to the read me with your findings

**Comment by juhhov** [comment]
> I'd rather the default handle the signals correctly and avoid all the wrappers and have auto updates be the side effect since most container use cases can't handle updates restarting the container

Container does not restart during update when using `/actions-runner/bin/runsvc.sh` command.

> Thanks however, I might add a snippet to the read me with your findings

:+1: Auto-update disable is the preferred solution in any case since github finally released it. Thanks for your work with the image!
