### ISSUE TITLE
add 'rsync' package in base image

### ISSUE THREAD

**Issue by yylt** [myoung34/docker-github-actions-runner#190]
build kubernetes failed because 'rsync' package not installed

**Comment by myoung34** [comment]
If youd like to start a PR I can make sure it works on the different OS/Arch in the build matrix

**Comment by brahmann** [comment]
Hi, its really needed rsync inside
(runnig in nomad, latest tag, x86_64)
@myoung34 can you add inside rsync?

**Comment by myoung34** [comment]
PRs are always welcome, just make sure it works for arm64/armhf/amd64 across the major ubuntu's please

**Comment by tomgrv** [comment]
Hi All

Created PR #212 for this.

Thank 🙏

**Comment by myoung34** [comment]
Once #211 gets through Ill merge #212 after slight testing and do some refactoring
