### ISSUE TITLE
dial tcp 127.0.0.1:5432: connect: connection refused

### ISSUE THREAD

**Issue by ifeelingz** [myoung34/docker-github-actions-runner#199]
![image](https://user-images.githubusercontent.com/6375304/163323687-869267e1-4d44-4629-8a6b-779c84fc7ed8.png)

dial tcp 127.0.0.1:5432: connect: connection refused

"[docker-github-actions-runner](https://github.com/myoung34/docker-github-actions-runner)" works great. But I got a problem when I simulate the Database and it can't connect.

Meanwhile, if I install it on Ubuntu without Docker, it works fine.

How should I fix this? Can recommend me ?

Best Regards.

**Comment by ifeelingz** [comment]
> Docker Support
> Please note that while this runner installs and allows docker, github actions itself does not support using docker from a self hosted runner yet. For more information:
> 
> https://github.com/actions/runner/issues/406
> https://github.com/actions/runner/issues/367
> Also, some GitHub Actions Workflow features, like [Job Services](https://docs.github.com/en/actions/guides/about-service-containers), won't be usable and https://github.com/myoung34/docker-github-actions-runner/issues/61.

Sorry., I got the answer.

**Comment by ifeelingz** [comment]
Just., Fixed IP !!

![image](https://user-images.githubusercontent.com/6375304/163377722-c678477a-6045-4ea6-8f2d-4ba312f31830.png)

**Comment by makarov-roman** [comment]
Hey @ifeelingz, can you elaborate a little bit more? As far I understand you starting new postgres container inside gh-runner, but then you trying to access it via public IP of machine, on which docker with runner works?
Do you have only one runner per machine?

**Comment by makarov-roman** [comment]
it works for me too. But it's more like workaround than solution. Every job with such database service has to be exposed on host machine, which makes it much harder to scale (both vertically and horizontally).

@myoung34 should we reopen the issue?

**Comment by myoung34** [comment]
To be honest I still dont understand the issue but this is more configuration than anything else. the runner has nothing to do with the networking configuration and is different per orchestrator. For all I know the issue here is solely related to docker-compose

**Comment by nmalaguti** [comment]
It looks like the solution was to expose the port on the docker host interface? I'm pretty sure `172.17.0.1` is usually the gateway IP in the default bridge network. Since the runner is on the same bridge network as the service containers, you're able to access them this way. If you're running multiple jobs concurrently you'll almost certainly run into port conflicts.

**Comment by myoung34** [comment]
`172.17.0.1` is indeed the docker gateway for the service itself to talk to the host.

IE if you run something on `8888` on `0.0.0.0` you can hit it from a container on `172.17.0.1:8888` in most common docker set up scenarios

This behavior is _very_ specific to docker itself and not other CRI's

**Comment by makarov-roman** [comment]
Thanks for your feedback. Although I understand that it's not specific to this repo, some lost souls like me who had workflows on self-hosted runner without docker and now have this issue would be greatly appreciate it if you could point in the right direction.

**Comment by jsoneaday** [comment]
Has anyone got this to work without using the 172 ip. I tried that ip and it still getting connection refused. Although I am not using a service for a docker compose up command

**Comment by myoung34** [comment]
If youre using docker 4 windows or mac it could be different, but it will be whatever the gateway is
