### ISSUE TITLE
Disable autoupdates with `--disableupdate` flag

### ISSUE THREAD

**Issue by adozzer** [myoung34/docker-github-actions-runner#203]
Now running docker instances fail to start if runner was updated. It starts an autoupdate procedure and restarts the process after finish, bringing down the container.
However, GitHub recently [released](https://github.blog/changelog/2022-02-01-github-actions-self-hosted-runners-can-now-disable-automatic-updates/) a feature for runners, which allows to not update automatically.
Can it be used?

**Comment by myoung34** [comment]
This is already supported. See the `DISABLE_AUTO_UPDATE` env var in the README.
