### ISSUE TITLE
Random RUNNER_NAME

### ISSUE THREAD

**Issue by rs-garrick** [myoung34/docker-github-actions-runner#21]
Thanks so much for your awesome docker image.  It's _almost_ perfect for me!

I'm setting up an ECS service to run your docker image. Github requires that each RUNNER_NAME be unique. There's really no way for an ECS service to assign unique values to each task run. If you could add an easy to add a random string suffix to the runner name, that would be amazing. I can provide a patch if you like. Something simple like $RUNNER_NAME-$RANDOM would be great.

**Comment by myoung34** [comment]
Done in https://github.com/myoung34/docker-github-actions-runner/commit/258480828a9232a6d7b2f3ce8469757e8d7e0601

You can use `RUNNER_NAME_PREFIX` to set the prefix.

Unfortunately you missed my auto-build of 2.263 about an hour ago but this should make its way into `latest` in the next few minutes


```
$ echo $RUNNER_NAME
github-runner-uQTSLJggSCcOF
```

or if `RUNNER_NAME_PREFIX` is `foo` (and `RUNNER_NAME` is not given):

```
$ echo $RUNNER_NAME
foo-kVnPzHIDa2Gv7
```

**Comment by rs-garrick** [comment]
That's hilarious!  This is _precisely_ what I needed.  Thank you very much.

**Comment by myoung34** [comment]
It was an easy commit for your request =)
