### ISSUE TITLE
Images for arm/v7 are no longer published?

### ISSUE THREAD

**Issue by bdovaz** [myoung34/docker-github-actions-runner#215]
@myoung34 Why did you stop publishing debian images in arm/v7 from 2.293 onwards? I have a RPI 4 and I used to put the tag "debian-bullseye" and it worked but now I have to put the last version that works with arm/v7 which is "2.292.0-debian-bullseye".

**Comment by myoung34** [comment]
Correct, no more arm v7

The drift is way too hard to manage for only raspberry pi 2's from a decade ago

If you have a raspberry pi 4 youll get better performance using arm64 which is supported by debian bullseye

If you update your pi host OS to something with arm64 this will all work

**Comment by bdovaz** [comment]
I know but upgrading an OS from 32 to 64 is not trivial as it requires a clean install and reconfiguring everything, you can't upgrade that easily.

The 64-bit version of Raspberry Pi OS has been released this year (Feb 2022) so it is something that was not possible until recently.
