### ISSUE TITLE
Can I use "EPHEMERAL" with docker run ?

### ISSUE THREAD

**Issue by ifeelingz** [myoung34/docker-github-actions-runner#217]
```
docker run -d --restart always --name github-runner \
  -e RUNNER_NAME_PREFIX="myrunner" \
  -e ACCESS_TOKEN="footoken" \
  -e RUNNER_WORKDIR="/tmp/github-runner-your-repo" \
  -e RUNNER_GROUP="my-group" \
  -e RUNNER_SCOPE="org" \
  -e DISABLE_AUTO_UPDATE="true" \
  -e ORG_NAME="octokode" \
  -e LABELS="my-label,other-label" \
  -v /var/run/docker.sock:/var/run/docker.sock \
  -v /tmp/github-runner-your-repo:/tmp/github-runner-your-repo \
  myoung34/github-runner:latest
```

If it works, how do I add the command?

Thank you.

**Comment by myoung34** [comment]
What command are you asking to add

**Comment by ifeelingz** [comment]
> What command are you asking to add


I want to know if I want to use --ephemeral 

After docker run -d --restart always --name github-runner \

How do I use it?

**Comment by myoung34** [comment]
the [usage is here](https://github.com/myoung34/docker-github-actions-runner/wiki/Usage#ephemeral-runners) basically set the env var `-e EPHEMERAL=1`
