### ISSUE TITLE
Agent restart

### ISSUE THREAD

**Issue by tk098398** [myoung34/docker-github-actions-runner#218]
Good afternoon, the agent is trying to update and restarts in a circle,again

https://github.com/myoung34/docker-github-actions-runner/issues/185

--------------------------------------------------------------------------------
|        ____ _ _   _   _       _          _        _   _                      |
|       / ___(_) |_| | | |_   _| |__      / \   ___| |_(_) ___  _ __  ___      |
|      | |  _| | __| |_| | | | | '_ \    / _ \ / __| __| |/ _ \| '_ \/ __|     |
|      | |_| | | |_|  _  | |_| | |_) |  / ___ \ (__| |_| | (_) | | | \__ \     |
|       \____|_|\__|_| |_|\__,_|_.__/  /_/   \_\___|\__|_|\___/|_| |_|___/     |
|                                                                              |
|                       Self-hosted runner registration                        |
|                                                                              |
--------------------------------------------------------------------------------
Cannot configure the runner because it is already configured. To reconfigure the runner, run 'config.cmd remove' or './config.sh remove' first.

√ Connected to GitHub

Current runner version: '2.292.0'
2022-06-15 04:45:07Z: Listening for Jobs
Runner update in progress, do not shutdown runner.
Downloading 2.293.0 runner
Waiting for current job finish running.
Generate and execute update script.
Runner will exit shortly for update, should be back online within 10 seconds.
Runner update process finished.
Runner reusage is disabled
Obtaining the token of the runner
Configuring

Is there anything wrong with it?

docker-compose.yml
version: '3.9'

services:
  runner:
    image: myoung34/github-runner:2.291.0
    environment:
      TZ: xxxxx
      RUNNER_NAME: runner
      RUNNER_SCOPE: enterprise
      RUNNER_WORKDIR: /tmp/runner/work1
      ENTERPRISE_NAME: xxxxxx
      LABELS: xxxxxx
      ACCESS_TOKEN: xxxx
    volumes:
      - '/var/run/docker.sock:/var/run/docker.sock'
      - '/tmp/runner:/tmp/runner'
    user: root

**Comment by myoung34** [comment]
you need to pass the flag that was posted in your linked issue. see [here](https://github.com/myoung34/docker-github-actions-runner/blob/master/entrypoint.sh#L75-L80)

**Comment by tk098398** [comment]
Thanks for your fast input. 
We added "DISABLE_AUTO_UPDATE" and upgraded the github-runner image 2.292.0,not image 2.291.0.
the container starts successfully!
