### ISSUE TITLE
ACCESS_TOKEN is available to build jobs

### ISSUE THREAD

**Issue by rs-garrick** [myoung34/docker-github-actions-runner#22]
Inside of a build job, the ACCESS_TOKEN env variable is still set. This should not be usable by builds. Please unset that variable in entrypoint.sh after it is used. Thanks!

**Comment by myoung34** [comment]
Good catch

resolved by https://github.com/myoung34/docker-github-actions-runner/commit/3d44159889d799f770a4a1e66771ae90a08122da

will be in latest images shortly

**Comment by myoung34** [comment]
I unresolved this with https://github.com/myoung34/docker-github-actions-runner/commit/7648aa420578fa0840a0886c20973c9ada716fa6

the access token is needed for deregistration

if you have a better way to handle this im all ears, but cleaning itself up seems like a good idea

Maybe an env var `REMOVE_TOKEN_ON_SIGTERM=true|false` if you dont want deregistration to happen by the runner itself so you can tie in some sort of side car?
