### ISSUE TITLE
Reboot loop after runner auto update

### ISSUE THREAD

**Issue by AleksaKolarski** [myoung34/docker-github-actions-runner#220]
After about a month of smooth running, this started happening today after I have recreated the container:
It would stay in reboot loop, and would not pick up any job.

Runner reusage is disabled
Obtaining the token of the runner
Configuring
--------------------------------------------------------------------------------
|        ____ _ _   _   _       _          _        _   _                      |
|       / ___(_) |_| | | |_   _| |__      / \   ___| |_(_) ___  _ __  ___      |
|      | |  _| | __| |_| | | | | '_ \    / _ \ / __| __| |/ _ \| '_ \/ __|     |
|      | |_| | | |_|  _  | |_| | |_) |  / ___ \ (__| |_| | (_) | | | \__ \     |
|       \____|_|\__|_| |_|\__,_|_.__/  /_/   \_\___|\__|_|\___/|_| |_|___/     |
|                                                                              |
|                       Self-hosted runner registration                        |
|                                                                              |
--------------------------------------------------------------------------------
Authentication
√ Connected to GitHub
Runner Registration
√ Runner successfully added
√ Runner connection is good
Runner settings
√ Settings Saved.
√ Connected to GitHub
Current runner version: '2.292.0'
2022-06-19 11:31:28Z: Listening for Jobs
Runner update in progress, do not shutdown runner.
Downloading 2.293.0 runner
Waiting for current job finish running.
Generate and execute update script.
Runner will exit shortly for update, should be back online within 10 seconds.
Runner update process finished.
Runner reusage is disabled
Obtaining the token of the runner
Configuring
--------------------------------------------------------------------------------
|        ____ _ _   _   _       _          _        _   _                      |
|       / ___(_) |_| | | |_   _| |__      / \   ___| |_(_) ___  _ __  ___      |
|      | |  _| | __| |_| | | | | '_ \    / _ \ / __| __| |/ _ \| '_ \/ __|     |
|      | |_| | | |_|  _  | |_| | |_) |  / ___ \ (__| |_| | (_) | | | \__ \     |
|       \____|_|\__|_| |_|\__,_|_.__/  /_/   \_\___|\__|_|\___/|_| |_|___/     |
|                                                                              |
|                       Self-hosted runner registration                        |
|                                                                              |
--------------------------------------------------------------------------------
Cannot configure the runner because it is already configured. To reconfigure the runner, run 'config.cmd remove' or './config.sh remove' first.
√ Connected to GitHub
Current runner version: '2.292.0'
2022-06-19 11:32:10Z: Listening for Jobs
Runner update in progress, do not shutdown runner.
Downloading 2.293.0 runner
Waiting for current job finish running.
Generate and execute update script.
Runner will exit shortly for update, should be back online within 10 seconds.
Runner update process finished.
Runner reusage is disabled
Obtaining the token of the runner
Configuring
--------------------------------------------------------------------------------
|        ____ _ _   _   _       _          _        _   _                      |
|       / ___(_) |_| | | |_   _| |__      / \   ___| |_(_) ___  _ __  ___      |
|      | |  _| | __| |_| | | | | '_ \    / _ \ / __| __| |/ _ \| '_ \/ __|     |
|      | |_| | | |_|  _  | |_| | |_) |  / ___ \ (__| |_| | (_) | | | \__ \     |
|       \____|_|\__|_| |_|\__,_|_.__/  /_/   \_\___|\__|_|\___/|_| |_|___/     |
|                                                                              |
|                       Self-hosted runner registration                        |
|                                                                              |
--------------------------------------------------------------------------------
Cannot configure the runner because it is already configured. To reconfigure the runner, run 'config.cmd remove' or './config.sh remove' first.
√ Connected to GitHub
Current runner version: '2.292.0'
2022-06-19 11:32:48Z: Listening for Jobs
Runner update in progress, do not shutdown runner.
Downloading 2.293.0 runner
Waiting for current job finish running.
Generate and execute update script.
Runner will exit shortly for update, should be back online within 10 seconds.
Runner update process finished.
Runner reusage is disabled
Obtaining the token of the runner
Configuring
...

**Comment by AleksaKolarski** [comment]
I was lazy to look at closed issues. Answer is there...

**Comment by ben-z** [comment]
@AleksaKolarski Which issue has the answer?

**Comment by AleksaKolarski** [comment]
@ben-z Not sure of issue id, but it hinted at setting env variable DISABLE_AUTO_UPDATE to true, which disables auto update.

**Comment by Cheaterman** [comment]
If I'm not mistaken, this env var is only taken into account when first registering the runner, is that correct? Setting it after the fact will print "disabling auto updates" everywhere in logs, but updates will still occur.
