### ISSUE TITLE
Support for Windows Runners?

### ISSUE THREAD

**Issue by ScottPierce** [myoung34/docker-github-actions-runner#221]
Right now we are only able to make linux based runners. Would something in a Windows Docker Image be possible? https://hub.docker.com/_/microsoft-windows-base-os-images

**Comment by myoung34** [comment]
Im always open for PRs but I dont have anything in the pipeline to build or test windows containers currently

**Comment by marlon-git** [comment]
what about this one ?

https://dev.to/pwd9000/create-a-docker-based-self-hosted-github-runner-windows-container-3p7e

**Comment by myoung34** [comment]
If someone were to add some matrix code to build windows, osx or non-ubuntu images I wouldnt be against it but that's not something that I personally have a need for and likely won't start, but happy to review and help push for one

**Comment by myoung34** [comment]
Noting this is a better ticket duped by #258

**Comment by myoung34** [comment]
Closing as stale

**Comment by SpriteOvO** [comment]
Just found a repository https://github.com/tiobe/docker-github-runner-windows which is based on this repo and supported Windows. Haven't tested it but looks fine from README.
