### ISSUE TITLE
Install `docker compose` plugin for ARM compatibility.

### ISSUE THREAD

**Issue by mrmachine** [myoung34/docker-github-actions-runner#222]
Now that "compose 2" is a native plugin for docker itself (e.g. `docker compose` is a native subcommand), can you please install it instead of (or in addition to) the 1.27 x86 only `docker-compose`?

**Comment by mrmachine** [comment]
I believe it should be as easy as `apt-get install docker-compose-plugin`, since docker engine is already installed via repository.

**Comment by myoung34** [comment]
If you want to scaffold a PR I'm happy to review it for accuracy across the different architectures

**Comment by rahulsurwade08** [comment]
Hey @mrmachine , I would love to contribute to this issue under Hacktoberfest. How can I get started?

**Comment by Uzlopak** [comment]
@RahulSurwade08 

First step is to get a computer with an ARM cpu.

**Comment by martin-g** [comment]
@Uzlopak I don't think one needs "a computer with ARM cpu" for this task.
As long as the Ubuntu repository is [setup](https://docs.docker.com/engine/install/ubuntu/#set-up-the-repository) the command above (`apt-get install docker-compose-plugin`) will work on both amd64 and arm64. The ARM64 package is at https://download.docker.com/linux/ubuntu/dists/focal/pool/stable/arm64/

But if one wants to test it then getting a free VM is easy - https://martin-grigorov.medium.com/github-actions-arm64-runner-on-oracle-cloud-a77cdf7a325a

**Comment by RahulSurwade08** [comment]
Hey, I would like to work on this issue. How can I get started?
