### ISSUE TITLE
Sudo No Longer working

### ISSUE THREAD

**Issue by SteveBox0** [myoung34/docker-github-actions-runner#225]
This has been working for a long time up until roughly 15 hours ago. 

sudo apt-get update
```
sudo: a terminal is required to read the password; either use the -S option to read from standard input or configure an askpass helper
Error: Process completed with exit code 1.
```

**Comment by nmalaguti** [comment]
This is likely due to https://github.com/myoung34/docker-github-actions-runner/pull/223.

The `runner` user is in the `sudo` group, but we might need to modify the sudoers file to allow `runner` to run `sudo` without a password.

**Comment by nmalaguti** [comment]
https://askubuntu.com/a/340669

Want to put up a PR appending

```
%sudo  ALL=(ALL) NOPASSWD: ALL
```

to `/etc/sudoers` in `Dockerfile.base`?

**Comment by SteveBox0** [comment]
I have just added the below as a temporary workaround. As I already got additional logic that destroys the container on each workflow run to match up with the hosted runners.

`docker exec CONTAINERNAME sh -c 'echo ''%sudo  ALL=\(ALL\) NOPASSWD: ALL'' >> \/etc\/sudoers'`

**Comment by myoung34** [comment]
I have a fix on its way out [here](https://github.com/myoung34/docker-github-actions-runner/commit/ab8b9d7e6bdb77010a8066d0c89ee747c3eea043)

**Comment by nmalaguti** [comment]
> I have a fix on its way out [here](https://github.com/myoung34/docker-github-actions-runner/commit/ab8b9d7e6bdb77010a8066d0c89ee747c3eea043)

Fix appears to work on the latest images on dockerhub.

**Comment by myoung34** [comment]
Thanks all!
