### ISSUE TITLE
container option in workflow

### ISSUE THREAD

**Issue by AlfonsoUceda** [myoung34/docker-github-actions-runner#232]
Hi!

Thanks for your amazing work. 

I'm using a workflow and works really well but I want to use `container` inside my job and fails. I've configured the workflow with the following value: `container: ubuntu:20.04` and the error that I receive in the CI is the following:

```
Error response from daemon: error while creating mount source path '/opt/hostedtoolcache': mkdir /opt/hostedtoolcache: read-only file system
Error: failed to start containers: 800173908b8340052e6fe49216fd8009d4f01b211dd665e507784c245d517517
Error: Docker start fail with exit code 1
```

Is not possible to use it? I thought was able to use it but without using docker inside that container.

Cheers

**Comment by myoung34** [comment]
can you post the full yaml youre using out of curiosity?
My gut says it wont work because of nested container support but thats not the error here

**Comment by AlfonsoUceda** [comment]
Hi @myoung34 finally I've changed the image so this question is not valid anymore. Thank you for your time!
