### ISSUE TITLE
GitHub CLI GPG key expired

### ISSUE THREAD

**Issue by Otterian** [myoung34/docker-github-actions-runner#236]
Hi,

https://github.com/cli/cli/issues/6175

The key that has been used to sign the GitHub CLI package has expired, and will cause errors on subsequent apt updates and apt installs unless apt is told otherwise.

It seems to me that they won't be renewing/adding new keys to sign that package, and will instead rely on workflows pulling directly from the release page (on GitHub)

This means that these lines must be scrapped https://github.com/myoung34/docker-github-actions-runner/blob/master/Dockerfile.base#L73-L77
Instead the build for this image can do a curl/wget to get the current stable release from https://github.com/cli/cli/releases/ and put it somewhere in PATH.

A temporary workaround for users that are hitting this issue in their workflows (if you are installing packages using apt):
`(sudo) rm /etc/apt/sources.list.d/github-cli.list`

**Comment by davidkarlsen** [comment]
Either that, or this image can go get the binary and put it into /usr/local/bin

**Comment by nmalaguti** [comment]
A 1-liner to replace the deb repo with: https://github.com/cli/cli/issues/6175#issuecomment-1236264607

**Comment by davidkarlsen** [comment]
@myoung34 do you have an updated image release?

**Comment by myoung34** [comment]
`:latest` has this fix
