### ISSUE TITLE
Browsers in Runner Image

### ISSUE THREAD

**Issue by nikeee** [myoung34/docker-github-actions-runner#237]
I'm currently in a situation where I need a locally installed Chromium and/or Firefox for E2E testing.

As installing one or multiple browsers would add siginificant size to the base image: Is this in the scope of this repository?
Would it be feasable to add another runner image (which is based on the base image) that also contains the latest browsers?

**Comment by myoung34** [comment]
If it's not listed [here](https://github.com/actions/runner-images/blob/main/images/linux/Ubuntu2204-Readme.md) then it's out of scope

**Comment by nikeee** [comment]
They list these browsers:
> # Browsers and Drivers
> Google Chrome 104.0.5112.101
> ChromeDriver 104.0.5112.79
> Chromium 104.0.5112.0
> Microsoft Edge 104.0.1293.70 (apt source repository: https://packages.microsoft.com/repos/edge)
> Microsoft Edge WebDriver 104.0.1293.70
> Selenium server 4.4.0

So no Firefox, but Chrome, Chromium and Edge. This would cover my use case for now.

The previous image also had [Firefox](https://github.com/actions/runner-images/blob/main/images/linux/Ubuntu2004-Readme.md#browsers-and-drivers). Don't know why it was dropped.

**Comment by nmalaguti** [comment]
I'd prefer the base image remain (relatively) small. I think if we want to make an image on top of a more full-featured base, we might want to look at https://github.com/nektos/act#runners. I'd be happy with providing both a small image and a larger, more complete base for users who need more.

**Comment by myoung34** [comment]
I'd also be onboard for a `-full` image add that adds more stuff like browsers and not pure languages to the image itself. 

There should be some patterns in place if you check the .github/workflow dir for building off the base and using that to build a -full image that adds the supported browsers

**Comment by nikeee** [comment]
Could we just use the [current Dockerfile](https://github.com/myoung34/docker-github-actions-runner/blob/master/Dockerfile) and use some act Runner as a base, as @nmalaguti suggested? This would also reduce some maintaining work on the image.

**Comment by myoung34** [comment]
Its possible, but if someone adds osx or windows or non-ubuntu later we'd be back at square one

I think its worth a PR to see what it would be up against but what I dont want to do is create drift: ie `latest` being different from `latest-full` since they would be **wildly** different

Honestly I'd like to see how to automate mine using [the actual runners base](https://github.com/actions/runner-images) and not ubuntu core but its not something ive had time for

**Comment by rahulsurwade08** [comment]
Hey @nikeee , I would love to contribute to this issue under Hacktoberfest. How can I get started?

**Comment by myoung34** [comment]
Closing for more info/context in #259
