### ISSUE TITLE
Support for Almalinux

### ISSUE THREAD

**Issue by raddessi** [myoung34/docker-github-actions-runner#247]
Hey there! First off thank you for getting this project together it has been incredibly useful :)

In the same direction as #221 I would like to add support for some almalinux runners that would provide the tags:
* `almalinux-8` from the upstream `almalinux:8`
* `almalinux-9` and `almalinux-latest` from the upstream `almalinux:9`

If this is still acceptable I'll get a PR going and send it over. Thanks again!

**Comment by myoung34** [comment]
Im not against it but im curious how complex itll be making it line up with ubuntu base

**Comment by raddessi** [comment]
Yeah me too. I'm hoping it's not too far off and mostly just a different package list, we will see i guess! Thanks for confirming
