### ISSUE TITLE
support for s390x

### ISSUE THREAD

**Issue by chantra** [myoung34/docker-github-actions-runner#248]
I am interested in having a s390x version of the runner so it can run on IBM cloud and test software on big-endian machines.

Currently, I am using https://github.com/libbpf/libbpf/tree/master/ci/rootfs/s390x-self-hosted-builder to do this, but would much prefer to have something that runs the same runner setup (scripts, env variable setup...) for both x86_64 and s390x.

Looking at https://github.com/myoung34/docker-github-actions-runner/blob/master/.github/workflows/base.yml#L38 and https://github.com/myoung34/docker-github-actions-runner/actions/runs/3141394647/jobs/5103778322#step:4:247 , at least s390x is an available platform so it is a good start to build automation around it.

I would happily work on this if this is something that you are willing to merge.

**Comment by myoung34** [comment]
If you submit a draft and it works across the major distros (all builds work) im good to add it

**Comment by chantra** [comment]
Great. Thanks for confirming. I will close that issue now and hopefully come up with a PR as soon as cycles can be spared.

**Comment by chantra** [comment]
https://github.com/actions/runner/issues/2263 would greatly help in getting native support for s390x!
