### ISSUE TITLE
Shouldn't have to provide REPO_URL for Org Runner

### ISSUE THREAD

**Issue by goughlee** [myoung34/docker-github-actions-runner#25]
When attempting to run an org runner. e.g.

```
docker run -e ACCESS_TOKEN="foo_token" 
           -e RUNNER_NAME="foo_runner_name" 
           -e ORG_RUNNER="true" 
           -e ORG_NAME="foo_org" ...
```

...configuration fails with...

`Invalid configuration provided for url. Terminating unattended configuration.`

Seems that PROTO is not set correctly when REPO_URL is omitted in entrypoint.sh in the ORG_RUNNER=true scenario.

**Comment by myoung34** [comment]
Good catch. Fixed in https://github.com/myoung34/docker-github-actions-runner/commit/5c2992ba3f034fd4ce3c942eec6b59b73d2d0e06 

should be in latest shortly
