### ISSUE TITLE
Update loop

### ISSUE THREAD

**Issue by flobernd** [myoung34/docker-github-actions-runner#251]
Hi there,

I'm experiencing an update loop when using your image. As soon as a new version is available, the runner keeps restarting itself in a loop:

<details>
  <summary>Docker Compose Log</summary>
  
```
runner-worker-1  | --------------------------------------------------------------------------------
runner-worker-1  | |        ____ _ _   _   _       _          _        _   _                      |
runner-worker-1  | |       / ___(_) |_| | | |_   _| |__      / \   ___| |_(_) ___  _ __  ___      |
runner-worker-1  | |      | |  _| | __| |_| | | | | '_ \    / _ \ / __| __| |/ _ \| '_ \/ __|     |
runner-worker-1  | |      | |_| | | |_|  _  | |_| | |_) |  / ___ \ (__| |_| | (_) | | | \__ \     |
runner-worker-1  | |       \____|_|\__|_| |_|\__,_|_.__/  /_/   \_\___|\__|_|\___/|_| |_|___/     |
runner-worker-1  | |                                                                              |
runner-worker-1  | |                       Self-hosted runner registration                        |
runner-worker-1  | |                                                                              |
runner-worker-1  | --------------------------------------------------------------------------------
runner-worker-1  | 
runner-worker-1  | # Authentication
runner-worker-1  | 
runner-worker-1  | 
runner-worker-1  | √ Connected to GitHub
runner-worker-1  | 
runner-worker-1  | # Runner Registration
runner-worker-1  | 
runner-worker-1  | 
runner-worker-1  | 
runner-worker-1  | 
runner-worker-1  | √ Runner successfully added
runner-worker-1  | √ Runner connection is good
runner-worker-1  | 
runner-worker-1  | # Runner settings
runner-worker-1  | 
runner-worker-1  | 
runner-worker-1  | √ Settings Saved.
runner-worker-1  | 
runner-worker-1  | 
runner-worker-1  | √ Connected to GitHub
runner-worker-1  | 
runner-worker-1  | Current runner version: '2.297.0'
runner-worker-1  | 2022-10-11 07:12:22Z: Listening for Jobs
runner-worker-1  | Runner update in progress, do not shutdown runner.
runner-worker-1  | Downloading 2.298.2 runner
runner-worker-1  | Waiting for current job finish running.
runner-worker-1  | Generate and execute update script.
runner-worker-1  | Runner will exit shortly for update, should be back online within 10 seconds.
runner-worker-1  | Runner update process finished.
runner-worker-1  | Runner reusage is disabled
runner-worker-1  | Obtaining the token of the runner
runner-worker-1  | Configuring
runner-worker-1  | 
runner-worker-1  | --------------------------------------------------------------------------------
runner-worker-1  | |        ____ _ _   _   _       _          _        _   _                      |
runner-worker-1  | |       / ___(_) |_| | | |_   _| |__      / \   ___| |_(_) ___  _ __  ___      |
runner-worker-1  | |      | |  _| | __| |_| | | | | '_ \    / _ \ / __| __| |/ _ \| '_ \/ __|     |
runner-worker-1  | |      | |_| | | |_|  _  | |_| | |_) |  / ___ \ (__| |_| | (_) | | | \__ \     |
runner-worker-1  | |       \____|_|\__|_| |_|\__,_|_.__/  /_/   \_\___|\__|_|\___/|_| |_|___/     |
runner-worker-1  | |                                                                              |
runner-worker-1  | |                       Self-hosted runner registration                        |
runner-worker-1  | |                                                                              |
runner-worker-1  | --------------------------------------------------------------------------------
runner-worker-1  | Cannot configure the runner because it is already configured. To reconfigure the runner, run 'config.cmd remove' or './config.sh remove' first.
runner-worker-1  | 
runner-worker-1  | √ Connected to GitHub
runner-worker-1  | 
runner-worker-1  | Current runner version: '2.297.0'
runner-worker-1  | 2022-10-11 07:14:34Z: Listening for Jobs
runner-worker-1  | Runner update in progress, do not shutdown runner.
runner-worker-1  | Downloading 2.298.2 runner
runner-worker-1  | Waiting for current job finish running.
runner-worker-1  | Generate and execute update script.
runner-worker-1  | Runner will exit shortly for update, should be back online within 10 seconds.
runner-worker-1  | Runner update process finished.
runner-worker-1  | Runner reusage is disabled
runner-worker-1  | Obtaining the token of the runner
runner-worker-1  | Configuring
runner-worker-1  | 
runner-worker-1  | --------------------------------------------------------------------------------
runner-worker-1  | |        ____ _ _   _   _       _          _        _   _                      |
runner-worker-1  | |       / ___(_) |_| | | |_   _| |__      / \   ___| |_(_) ___  _ __  ___      |
runner-worker-1  | |      | |  _| | __| |_| | | | | '_ \    / _ \ / __| __| |/ _ \| '_ \/ __|     |
runner-worker-1  | |      | |_| | | |_|  _  | |_| | |_) |  / ___ \ (__| |_| | (_) | | | \__ \     |
runner-worker-1  | |       \____|_|\__|_| |_|\__,_|_.__/  /_/   \_\___|\__|_|\___/|_| |_|___/     |
runner-worker-1  | |                                                                              |
runner-worker-1  | |                       Self-hosted runner registration                        |
runner-worker-1  | |                                                                              |
runner-worker-1  | --------------------------------------------------------------------------------
runner-worker-1  | Cannot configure the runner because it is already configured. To reconfigure the runner, run 'config.cmd remove' or './config.sh remove' first.
runner-worker-1  | 
runner-worker-1  | √ Connected to GitHub
runner-worker-1  | 
runner-worker-1  | Current runner version: '2.297.0'
runner-worker-1  | 2022-10-11 07:14:49Z: Listening for Jobs
```
  
</details>

I'm using the following `docker-compose.yml` file which is basically the one provided in your wiki:

```yaml

version: '2.3'
services:
  worker:
    image: myoung34/github-runner:latest
    environment:
      ACCESS_TOKEN: {REDACTED}
      REPO_URL: https://github.com/{REDACTED}/{REDACTED}
      RUNNER_WORKDIR: /tmp/runner/work
      RUNNER_SCOPE: 'repo'
      LABELS: linux,x64,integration-tests
    security_opt:
      # needed on SELinux systems to allow docker container to manage other docker containers
      - label:disable
    volumes:
      - '/var/run/docker.sock:/var/run/docker.sock'
      - '/tmp/runner:/tmp/runner'
      # note: a quirk of docker-in-docker is that this path
      # needs to be the same path on host and inside the container,
      # docker mgmt cmds run outside of docker but expect the paths from within
```

Docker version:

```
[ec2-user@ip-172-31-75-63 runner]$ docker version
Client:
 Version:           20.10.17
 API version:       1.41
 Go version:        go1.18.3
 Git commit:        100c701
 Built:             Thu Jun 16 20:08:47 2022
 OS/Arch:           linux/amd64
 Context:           default
 Experimental:      true

Server:
 Engine:
  Version:          20.10.17
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.18.3
  Git commit:       a89b842
  Built:            Thu Jun 16 20:09:24 2022
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.6.6
  GitCommit:        10c12954828e7c7c9b6e0ea9b0c02b01407d3ae1
 runc:
  Version:          1.1.3
  GitCommit:        1e7bb5b773162b57333d57f612fd72e3f8612d94
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```

Docker Compose Version:

```
[ec2-user@ip-172-31-75-63 runner]$ docker compose version
Docker Compose version v2.10.2
```

I'm aware of the `DISABLE_AUTO_UPDATE` option, but we would like to always use the latest runner, so enabling this is not an ideal solution.

**Comment by cduverne** [comment]
+1 Same behaviour here...

**Comment by myoung34** [comment]
This is the expected behavior
The upstream runner code will bounce the PID when a new version is downloaded unless updates are available

**Comment by flobernd** [comment]
How can this be the expected behavior? The container keeps downloading the new version, restarts, uses the **old** version again, detects a new version is available, downloads the new version again, restarts again, ... and so on.

This effectively breaks our selfhosted runner every single time GH releases a new runner update. It's not picking up any job and just gets stuck in the update loop.

**Comment by myoung34** [comment]
Containers are stateless. If PID0 dies the container will die as a result
The upstream runner code will download the version and kill off the runner process causing it to bounce. You can either disable updates or use `:latest`
 
This behavior is due to the upstream runner project and is expected behavior on their side. This container just falls under that.

**Comment by myoung34** [comment]
This is the PR in question https://github.com/actions/runner/pull/1558

If you have any questions about how updates work I suggest a ticket there, but this project has nothing to do with how the app updates

**Comment by flobernd** [comment]
@myoung34 I think we are talking about different topics. I **want** our runners to automatically update. It's just that the update is not persisted in the container for some reason.. This causes the update to get executed in an endless loop, because always the old version is started again after the container restart.

Edit: Wouldn't it make sense to add an option to preserve state? With a configurable directory similar to the runner working directory?

**Comment by myoung34** [comment]
Right the container exits when an update is made due to how containers and PID0 work

The code is not persisted across container exits

This would work if you point to `latest` since I rebuild that immediately via automation when an update upstream is available

**Comment by nmalaguti** [comment]
This is a really common gotcha. I think the expectation is that if you don't disable auto-updates that the same container will continue running, the runner process will just update itself.

I think we should make disable auto updates the default behavior because it can't ever really succeed and then add documentation about the best way to deal with regular github runner updates.

**Comment by flobernd** [comment]
Yes, exactly. My expectation (based on experience with other common container services) is that the container preserves state in a way that it would use the updated version on the next start. I did not even expect the same container to keep running, but I expected the restarted instance to use the previously downloaded update.

I'm pointing to "latest" already, but e.g. docker-compose does not automatically pull new images unless you manually recreate the container.

If somehow possible it would be really cool to be able to persist the container state. If not, making the DISABLE_UPDATES the default would definitely make sense to me. At least this would prevent such surprises like completely broken runners 🙂

**Comment by myoung34** [comment]
This isnt state to preserve, this is the actual runner code.
If you have any ideas or requests this is better suited for https://github.com/actions/runner

This project has nothing to do with the upstream code, only the packaging and runtime configuration of it

**Comment by nmalaguti** [comment]
> This isnt state to preserve, this is the actual runner code.

Completely agree, but it's been exposed here in a way that leads the user down a bad path. The first time I set this up I assumed that I didn't want to disable auto-updates because I expected it to "work" with the container. Then on the first update to the runner code, my containers were stuck in a reboot loop and I had no idea why.

The reality is that the default container configuration should be to disable auto-updates and in the README tell users that if they want to be on the latest version they should pull the `latest` tag nightly and restart their containers (which is what I did).

**Comment by flobernd** [comment]
Just for my understanding: If I would start the runner natively without the container - it would not be able to update itself as well?

I mean, the upstream runner code probably downloads the new version to some folder and starts it afterwards. 

I do completely understand if you don't want to implement this, but the update file should exist inside the container filesystem at this point and could be detected by the entrypoint script. Conditionally starting the new version should be possible. Of course this would make the container somewhat stateful. In combination with a "restart: always" policy, this could allow for always up-to-date runner executables inside the container.

I'm only speculating about the upstream runners update process here, so excuse me if I just made incorrect assumptions.

**Comment by myoung34** [comment]
If someone can draft a working pr for what that would look like I'd be ok with it but currently it's not something that I'm personally interested in implementing. I'm not against it if there's a working draft to iterate on though
