### ISSUE TITLE
chown in entrypoint.sh slows down ephemeral startup

### ISSUE THREAD

**Issue by lumagi** [myoung34/docker-github-actions-runner#267]
The `entrypoint.sh` script does some chowning when not running as root (see [entrypoint.sh](https://github.com/myoung34/docker-github-actions-runner/blob/b89c3a1c850ca1cdeba77f16c0af4dbfca527251/entrypoint.sh#L156)). This also extends to the `/opt/hostedtoolscache` directory. If I place pre-installed tools into the directory during image creation, the startup time goes up by a significant factor. I don't know all potential side-effects, but to me it looks like `/opt/hostedtoolscache` is normally created a startup? Would it be possible to only chown the top-level directory?
If you agree with me, I can open a pull request to change this.

**Comment by Uzlopak** [comment]
Imho if the PR is not a big, you should simply provide it.

**Comment by myoung34** [comment]
> I don't know all potential side-effects, but to me it looks like /opt/hostedtoolscache is normally created a startup? Would it be possible to only chown the top-level directory?

I'd value testing that before a PR also. I don't know what side effects there are either but running it as a non privileged user and not chowning that directory seems like things won't work as expected

**Comment by lumagi** [comment]
@Uzlopak You are correct, it is probably easier if I open a pull request. Please see #268.
