### ISSUE TITLE
Add note regarding RUNNER_WORKDIR volume mount

### ISSUE THREAD

**Issue by EmpireJones** [myoung34/docker-github-actions-runner#27]
I spent the good part of a day trying to understand why github actions were behaving differently when using a local runner, compared to on github's runners. In particular, I was getting "file not found" errors when using actions, but when I did an `ls` on the files, via a workflow `run` command, the files were showing up just fine.

I believe what was happening is that because i was running the actions-runner in a docker container with the docker socket mounted from my host system, any docker actions would get a volume mount from the HOST system, rather than the runner's container.

The cause of things not working is that I was binding the RUNNER_WORKDIR to a different folder path on the host system, so the action runner container would see one thing, but the docker actions themselves would see another, because RUNNER_WORKDIR didn't exist on the host system.

It'd likely be good to add a note indicating that RUNNER_WORKDIR must exist on the host system and be the bind-mounted volume for RUNNER_WORKDIR in the container. Hopefully this saves others some time! 👍

**Comment by myoung34** [comment]
Theres a precursor note about RUNNER_WORKDIR at https://github.com/myoung34/docker-github-actions-runner/blob/master/README.md

If you want to type up more information to help others in the situation, Id be happy to merge it in

**Comment by myoung34** [comment]
Closed in #28 

Thanks again!

**Comment by myoung34** [comment]
This will be out shortly in `latest-*` tags on docker hub
