### ISSUE TITLE
Running a container on Mac gives mount errors

### ISSUE THREAD

**Issue by rjbaat** [myoung34/docker-github-actions-runner#272]
Hi, I am trying to run the runner locally on a MacBook M1, but when I have a action step that uses a docker container I get mount troubles. I don't see a way to set these mount points to a different path f.e. with an ENV. 

I used the docker run command from the wiki: https://github.com/myoung34/docker-github-actions-runner/wiki/Usage#org-runner

But I get errors like: 
```
The path /actions-runner/externals is not shared from the host and is not known to Docker.
```
and:
```
The path /opt/hostedtoolcache is not shared from the host and is not known to Docker.
```
Is there a way around this?

**Comment by myoung34** [comment]
Can you post your config (yaml or command etc) youre using to run and configure the runner?

**Comment by rjbaat** [comment]
Yes, I started the container on my MacBook with the following command:

```
docker run -d \
  --restart always \
  --name github-runner-0 \
  -e RUNNER_NAME_PREFIX="Macbook-M1-0" \
  -e ACCESS_TOKEN="xxxxxxxxxxx" \
  -e RUNNER_WORKDIR="/tmp/github-runner/Macbook-M1-0" \
  -e RUNNER_SCOPE="org" \
  -e DISABLE_AUTO_UPDATE="true" \
  -e ORG_NAME="xxxxxxx" \
  -e LABELS="macos" \
  -v /var/run/docker.sock:/var/run/docker.sock \
  -v /tmp/github-runner/Macbook-M1-0:/tmp/github-runner/Macbook-M1-0 \
  myoung34/github-runner:latest
```

Are there ENVs I missed?

**Comment by rjbaat** [comment]
@myoung34 I have looked a bit further and it looks like there are basically 3 volumes that are tried to mount when the container is created by the runner:
```
-v "/actions-runner/externals":"/__e":ro \
-v "/opt/hostedtoolcache":"/__t" \
-v "/tmp/github-runner/Macbook-M1-0":"/__w" \
```
The first 2 paths are mounted on a not allowed path on the macOS filesystem. 
If this was to be set by an ENV so you can determine where the mount than that would be great. 
Or if you adjust the folder to some path that is by default allowed by macOS like below, it would be cool to: 
```
/Users
/Volumes
/private
/tmp
/var/folders
```
With this adjustment I think the runner would be able to spin up containers and run on Mac. 

Is this something you can adjust for Mac users?

**Comment by myoung34** [comment]
This is very heavily specific to a lot of helper functions in docker for mac which Im apt to not patch for

The issue here isnt with github actions or docker at all, its simply some internal implementation details on docker for mac

Unfortunately the best I can do is document it if you can give me what youd like here to document, but I dont wish to code this into the project itself since its very unrelated overall

**Comment by Ryangr0** [comment]
Very unfortunate this wasn't handled differently in my opinion. Both /actions-runner/externals and /opt/hostedtoolcache are not allowed on many systems, not just Mac with Docker (although not being able to test runners locally is a big drawback already). That's where I *first* saw these issues. After moving the entire thing to our servers and just resigning myself to testing on live, I'm running into permission issues on there, too. I don't see why there are so many different paths that need to be mounted, to begin with, and I'd like to understand. I can't find any information surrounding this anywhere.
