### ISSUE TITLE
Make Dockerfile easier to patch

### ISSUE THREAD

**Issue by koendv** [myoung34/docker-github-actions-runner#274]
Hi. I'm using your "github actions runner in a docker". I patch the Dockerfile to run on linux/arm64 with ```ARG TARGETPLATFORM="linux/arm64"```. Unfortunately, that is the line just after the github runner version. So every time the github runner version changes the patch fails. 
Could you put a few lines before and after ``ARG GH_RUNNER_VERSION``, like in the attached file, 
[Dockerfile.txt](https://github.com/myoung34/docker-github-actions-runner/files/10465103/Dockerfile.txt), to keep the github runner version a bit separate from other variables? Thanks.

**Comment by myoung34** [comment]
If you have a fix handy I'm happy to review it for sure

**Comment by koendv** [comment]
OK.
What I have is that patches to Dockerfile change whenever GH_RUNNER_VERSION changes.
What is propose is that in the Dockerfile the three lines before, and the three lines after 
```
ARG GH_RUNNER_VERSION="2.302.1"
```
contain no variables, just text. e.g.:
```
RUN mkdir -p /opt/hostedtoolcache


#  GH_RUNNER_VERSION
ARG GH_RUNNER_VERSION="2.302.1"



ARG TARGETPLATFORM
```
That way, patches for AGENT_TOOLSDIRECTORY ot TARGETPLATFORM do not contain the github runner version number. 

Thank you.

**Comment by myoung34** [comment]
If you can get a PR up that would clarify things better
