### ISSUE TITLE
`_RUNNER_NAME` does not given properly when runs container on Cloud Run and ECS

### ISSUE THREAD

**Issue by Kesin11** [myoung34/docker-github-actions-runner#275]
## Description
The runner name is not given randomly when using v2.301.1 with Cloud Run and ECS on Fargate.

I'm running self-hosted runner on Google Cloud Cloud Run Job and AWS ECS on Fargate with my custom image based on this repository. Since the release of `myoung34/github-runner:2.301.1` my runners could not launch concurrently.
The reason is that all runners try to use the same name, but GitHub does not accept the same runner name as you know.

- Cloud Run job: `${RUNNER_NAME_PREFIX}-worker`. 
- ECS on Fargate: `{RUNNER_NAME_PREFIX}-` 

https://github.com/myoung34/docker-github-actions-runner/pull/271 changed to get random string from /etc/hostname instead of self generated random string, but some container platform does not provide random string.
In my expectation, Cloud Run Job provide fix hostname `worker` and ECS on Fargate provide empty string or maybe /etc/hostname does not exist.

## Solutions I would expect
Could you add new option that user can choose previous behavior that generates random string as `_RUNNER_NAME` ? Or please revert to https://github.com/myoung34/docker-github-actions-runner/pull/271.

**Comment by myoung34** [comment]
@Kesin11 I dont have access to ECS this moment

Can you tell me if `/etc/hostname` exists or is does it exist but is empty? That will help me come up with a solution that works both ways

**Comment by Kesin11** [comment]
I tried run two commands in same my custom runner image with ECS on Fargate.

`error: exec: "ls -al /etc/hostname": stat ls -al /etc/hostname: no such file or directory`
`error: exec: "cat /etc/hostname": stat cat /etc/hostname: no such file or directory`

it seems `/etc/hostname` does not exist.

**Comment by myoung34** [comment]
@Kesin11 if youd like to test #276 I can merge and deploy it to `:latest`

**Comment by Kesin11** [comment]
@myoung34 
Thank you! I'll try it. However, I think checking for existence of /etc/hostname works for ECS but doesn't work for Cloud Run.
My Cloud Run runner name `Cloud Run job: ${RUNNER_NAME_PREFIX}-worker` shows it has /etc/hostname but it contain same string `worker`, so #276 won't solve this problem when using Cloud Run.

**Comment by Kesin11** [comment]
I've just tried #276 with ECS on Fargate however it doesn't fixed. I commented detail to #276.

**Comment by myoung34** [comment]
@Kesin11 i updated the PR with some new behavior and a new environment variable

If you set `RANDOM_RUNNER_SUFFIX` to anything other than `true` it will check if /etc/hostname exists and is not empty and use that with a fallback to a random string.

If you set `RANDOM_RUNNER_SUFFIX` to `true` (or dont set it at all, default is `true`) it will just use the randomized string.

This should let the previous random string be the default but let you attempt to use /etc/hostname with some fallback mechanisms

this means:
*  in cloud run you can set nothing and not pick up the non-unique `worker`, it will just randomize.
* in ecs you can set `RANDOM_RUNNER_SUFFIX` to `false` and pick up /etc/hostname if it had contents, but will fallback to random safely
* In any other platform if `RANDOM_RUNNER_SUFFIX` is `false` and /etc/hostname is the container ID it works as #271 requested
* If anyone wishes to use neither of these they can use `RUNNER_NAME` and override all of this behavior outright

If you can test this ill deploy it and update docs if it fixes it for you but this should add a lot of safe functionality

**Comment by Kesin11** [comment]
Thank you! I'll try it soon.

**Comment by HieronyM** [comment]
Sorry to reply on closed issue,
but I'm wondering, is it possible to append the ECS task ID/ECS container runtime ID on the runner?

So far I can only append the hostname by set `RANDOM_RUNNER_SUFFIX` to `false`. But I don't think the information enough, to execute stop the ECS task (after the task done, `workflow_job.completed` webhook event sent I want to terminate the ECS Task)

**Comment by HieronyM** [comment]
I found a good article here, and it seems possible to use container ID https://medium.com/dazn-tech/github-self-hosted-runners-on-ecs-f0f7182a3297

Here's the part to set the runner name to use container ID,
https://gist.github.com/jbdazn/cc34871a384502d52480f6419d208bd7#file-entrypoint-sh-L76-L80

**Comment by Kesin11** [comment]
@HieronyM 
When the container's entrypoint command terminates, the ECS task will also terminate. If `EPHEMERAL` is enabled, the container will also terminate when the github actions job terminates, so there is no need to terminate the ECS task.

**Comment by HieronyM** [comment]
@Kesin11 ,
ahh noted, but it doesn't change the ECS desired size right (ECS will create another Task and it will be idle if there's no job)

I was planning something like this for the autoscaler,

```
    # Check if the state of the workflow job is "queued" or "completed"
    job_status = payload['workflow_job']['status']

    if job_status == 'queued':
        add_runner(1)
    elif job_status == 'completed':
        remove_runner(runner_id)
```

My idea is, if there's a webhook event with state `workflow_job.queued` I will spawn 1 ECS runner, and terminates the runner when the state is `workflow_job.completed`

**Comment by HieronyM** [comment]
Correction, it works now.
instead of using tasks in a service, I can use ECS Standalone task.
