### ISSUE TITLE
Allow sourcing of env vars from file/secrets

### ISSUE THREAD

**Issue by mmastrac** [myoung34/docker-github-actions-runner#278]
The current setup requires hardcoding access tokens in `docker-compose.yml` files (or the equivalent), but docker's secrets infrastructure is a little bit more secure overall.

Ideally an environment variable could be used, and if that variable is set, `entrypoint.sh` would source that file before running anything else. The user could then create a local secret file, and specify it like so:

`ENV_FILE=/var/run/secrets/my-secrets`

The secrets file would be a set of environment key/value pairs, though it would likely just be an `ACCESS_TOKEN` or `RUNNER_TOKEN` entry:

`ACCESS_TOKEN=xyz`

**Comment by myoung34** [comment]
Can you not use the `.env` file method documented [here](https://docs.docker.com/compose/environment-variables/set-environment-variables/) ?

or `env_file: ` [here](https://docs.docker.com/compose/environment-variables/set-environment-variables/#use-the-env_file-attribute)

**Comment by mmastrac** [comment]
That works! I would prefer something that explicitly supports the secrets infrastructure, but it's a good enough workaround for what I need. Thanks for the heads-up.

**Comment by myoung34** [comment]
Environment variables are never secret, but alternatively id rather keep this container unaware of the orchestration nuances
