### ISSUE TITLE
Connect to docker instance thru TCP

### ISSUE THREAD

**Issue by yorqat** [myoung34/docker-github-actions-runner#287]
I found myself in a situation where I want  runner instances to use the same docker server. however It seems the only way is to mount a socket into the container, I'm wondering if there's a way to connect to another docker server over TCP

**Comment by myoung34** [comment]
This is more of a docker question, but you need to set up the docker daemon to use the tcp socket. it works as expected though

```
✗ docker run -it -e DOCKER_HOST=tcp://172.17.0.1:2375 --entrypoint /bin/bash myoung34/github-runner:latest

root@3a12fcc41620:/actions-runner# docker ps
CONTAINER ID   IMAGE                           COMMAND       CREATED         STATUS        PORTS     NAMES
3a12fcc41620   myoung34/github-runner:latest   "/bin/bash"   2 seconds ago   Up 1 second             brave_wilson
```
