### ISSUE TITLE
Now Docker already supported ARM based

### ISSUE THREAD

**Issue by trungdlp-wolffun** [myoung34/docker-github-actions-runner#290]
Check issue in README.md: https://github.com/docker/compose/issues/6831
Announcement: https://www.docker.com/blog/getting-started-with-docker-for-arm-on-linux/

Please remove this:
<img width="887" alt="image" src="https://user-images.githubusercontent.com/93299415/229403834-c9d32c1c-58a1-439b-add8-e5b7031c5341.png">

**Comment by myoung34** [comment]
If you have a pr to submit to enable this I can remove that but removing it from the readme won't add it to this image
