### ISSUE TITLE
Update baseimage to Ubuntu 22.04.x

### ISSUE THREAD

**Issue by VA-PLE** [myoung34/docker-github-actions-runner#294]
Version 20.04 uses Python 3.8. Some software has already stopped supporting this version. For example: new ansible and ansible-lint require Python >=3.9. Maybe you should upgrade the version of the base image to 22.04 (Python 3.10)?

**Comment by myoung34** [comment]
I'm not installing a specific version of python, only whatever the upstream packages contain, so I'm not sure I follow

**Comment by VA-PLE** [comment]
Ubuntu 20.04 python3 upstream packages: v3.8
Ubuntu 22.04 python3 upstream packages: v3.10
https://github.com/myoung34/docker-github-actions-runner/blob/a911c0ae5226ea288dfa34fb79f91dc662c7384a/Dockerfile.base#LL1C1-L1C1
Upgrade to a new version of Ubuntu to get the new version python3

**Comment by myoung34** [comment]
I'm not pinning any versions and don't wish to. That includes focal, as I'm not pinning to a minor version there either 

If I were concerned for one version of python I'd have to be concerned with the entire matrix of os type to version to python version

My suggestion is if you need a specific version of python in your steps and the upstream version here isn't enough is to guarantee it as a step with a non system python
