### ISSUE TITLE
CUDA enabled container

### ISSUE THREAD

**Issue by arunoruto** [myoung34/docker-github-actions-runner#300]
Would there be something against a CUDA enabled docker image? I guess, since the images from nvidia are based on ubuntu too, there shouldn't be much difference between your base image and their runtime image to configure it.
If you don't have much time, I could do some testing to try it out!

**Comment by myoung34** [comment]
I'm not against it depending on what the end result looks like, but if it requires additional or large software installed then it's probably of scope vs forking this project or using it as the upstream for a forked agent

**Comment by compscidr** [comment]
One thing you could do is use this image as a base and then create a new container on top of it. I have a setup like this where I add a jvm and android jdk install on top of it if you're interested to see what something like that might look like: https://github.com/compscidr/docker-github-actions-runner-android

**Comment by myoung34** [comment]
Going to close this as out of scope. I've had a few tickets in the past that expand on this. I'm all for forks, but the purpose of this container is very specifically for a minimal actions container
