### ISSUE TITLE
`/usr/bin/chown` not found on Debian Bulleyes

### ISSUE THREAD

**Issue by CircuitCoder** [myoung34/docker-github-actions-runner#304]
`chown` is located at `/usr/chown` in Debian Bulleyes, which was released prior to the [usr merge](https://wiki.debian.org/UsrMerge).

This caused the entrypoint script to fail when RUN_AS_ROOT is set to false (https://github.com/myoung34/docker-github-actions-runner/blob/master/entrypoint.sh#L189)

**Comment by myoung34** [comment]
Strange, good catch

PR shortly
