### ISSUE TITLE
Run as helm chart 

### ISSUE THREAD

**Issue by autotune** [myoung34/docker-github-actions-runner#317]
It would be great if https://github.com/myoung34/docker-github-actions-runner/wiki/Usage#kubernetes could be converted to a helm chart. Happy to help if this sounds like a good idea @myoung34

**Comment by myoung34** [comment]
I'm less inclined to make it an actual helm chart since the scope is just the runner, but I'm willing to host one if someone has ideas. It would be a different repo for 'single responsibility' though

**Comment by myoung34** [comment]
Going to close this as this repo is specifically not aimed at kubernetes, only running the actions container
