### ISSUE TITLE
Cannot register org runner

### ISSUE THREAD

**Issue by jupe** [myoung34/docker-github-actions-runner#32]
I'm trying to deploy org self-hosted runner but something goes wrong, see above logs.
repo specific runner seems to work fine.

Q: Why org runner deployment require `REPO_URL` environment variable ?

```
# Authentication


Http response code: NotFound from 'POST https://api.github.com/actions/runner-registration'

{"message":"Not Found","documentation_url":"https://developer.github.com/v3"}

Response status code does not indicate success: 404 (Not Found).
```

**Comment by jupe** [comment]
https://github.com/myoung34/docker-github-actions-runner/issues/25 related to this, right ?

**Comment by myoung34** [comment]
You don't need `REPO_URL`, I just updated the docs a bit to make that more obvious (it seemed a bit confusing)

The minimum for an org runner: 

```
docker run -d --restart always --name github-runner \
  -e ACCESS_TOKEN="footoken" \
  -e RUNNER_NAME_PREFIX="myrunner" \
  -e RUNNER_WORKDIR="/tmp/github-runner-your-repo" \
  -e ORG_RUNNER="true" \
  -e ORG_NAME="octokode" \
  -e LABELS="my-label,other-label" \
  -v /var/run/docker.sock:/var/run/docker.sock \
  -v /tmp/github-runner-your-repo:/tmp/github-runner-your-repo \
  myoung34/github-runner:latest
```

the minimum for a repo runner:

```
docker run -d --restart always --name github-runner \
  -e REPO_URL="https://github.com/myoung34/repo" \
  -e RUNNER_NAME="foo-runner" \
  -e RUNNER_TOKEN="footoken" # or ACCESS_TOKEN \
  -e RUNNER_WORKDIR="/tmp/github-runner-your-repo" \
  -v /var/run/docker.sock:/var/run/docker.sock \
  -v /tmp/github-runner-your-repo:/tmp/github-runner-your-repo \
  myoung34/github-runner:latest
```

**Comment by jupe** [comment]
@myoung34 should `RUNNER_TOKEN` still works without `ACCESS_TOKEN` ?

**Comment by myoung34** [comment]
If you provide it a runner token, yes. Runner tokens are short lived though

They're interchangeable, the only difference is that access tokens are longer lived and create runner tokens at container start
