### ISSUE TITLE
Restart runner

### ISSUE THREAD

**Issue by tabossert** [myoung34/docker-github-actions-runner#33]
I wanted to have the container restart after running a workflow to get a fresh container for each workflow.  Is that possible? 

Thanks

**Comment by myoung34** [comment]
Thats not possible in self hosted, no. You could try to send a SIGTERM or SIGKILL to the container somehow in the action but im not sure how that would go. You can ask in https://github.com/actions/runner/issues to see if thats possible with `runsvc.sh` which is what this container wraps.

**Comment by tabossert** [comment]
Thanks @myoung34 I did try that and it ends up making the workflow never finish due to post actions from things like checkout.

I will open an issue with the repo you suggested above to ask.

**Comment by tabossert** [comment]
Thanks for suggestion, got an answer quickly on it
https://github.com/actions/runner/issues/559#issuecomment-646873454

It's on the roadmap and seems like it will be coming soon
