### ISSUE TITLE
Q: "Full" runner images

### ISSUE THREAD

**Issue by basz** [myoung34/docker-github-actions-runner#331]
I'm sure this has been asked before. But is it true that these provided runner images are not equivalent to github own images to run actions? I seem to need to manually install chromium that comes 'for free' with github runners.

I would love a 'full' variant even if it's big.

https://github.com/actions/runner-images/releases/tag/ubuntu22%2F20231016.1

**Comment by myoung34** [comment]
I'd like to keep parity, so if its officially installed and there's a consistent way to install it across the OS matrix I support I'm all for PR's

**Comment by naikrovek** [comment]
note that the link above is what's installed for a VM image.  

GitHub have a few Dockerfiles for containerized runners, one of which is here: https://github.com/actions/runner/blob/main/images/Dockerfile but it is _extremely_ basic.

Others can be found here: https://github.com/actions/actions-runner-controller/tree/master/runner

The standard "full-fat" images won't work without modification, which means you'll need to maintain the modifications.  Several pieces of software are installed as services, for example, and containers don't support systemd, which means these software packages won't install.
