### ISSUE TITLE
Missing `pkg-config`

### ISSUE THREAD

**Issue by Daniel-Aaron-Bloom** [myoung34/docker-github-actions-runner#337]
`pkg-config` is available on the GitHub runners by default, but not this image. It would be nice if it was there.

**Comment by myoung34** [comment]
Happy to merge a PR if you have one that works on all variations

**Comment by Daniel-Aaron-Bloom** [comment]
Doesn't seem like this actually got included in the [published image](https://hub.docker.com/layers/myoung34/github-runner/latest/images/sha256-021c63e48d83a7a1ce6cdf0164b92fd00a4a779d65bd018eb57eb6fc01b6329f?context=explore) (Step 16 shows `gosu`, but not `pkg-config`). I'm not super familiar with how pushing to dockerhub works.

Might be related to [this error](https://github.com/myoung34/docker-github-actions-runner/actions/runs/6936095785/job/18867550554), which looks like some kind of (possibly spurious) [keyserver error](https://github.com/myoung34/docker-github-actions-runner/actions/runs/6936095785/job/18867550554#step:8:9980). Maybe just needs to be retried?

**Comment by myoung34** [comment]
Should be out now

**Comment by myoung34** [comment]
Sometimes dockerhub rejects images
