### ISSUE TITLE
Provide Ubuntu 22.04 Based Images

### ISSUE THREAD

**Issue by timnolte** [myoung34/docker-github-actions-runner#339]
The `ubuntu-latest` for GitHub Runners is now 22.04 as of last year. I'm finding some software that is required to build Dev Containers using the official GitHub Actions not available on the 20.04 based Ubuntu and this is preventing me from being able to have consistent build environments without having to manually build from source on my self-hosted runner. I use both GitHub Runners & self-hosted as my self-hosted runners are on arm64.

https://docs.github.com/en/actions/using-github-hosted-runners/about-github-hosted-runners/about-github-hosted-runners#supported-runners-and-hardware-resources
> The ubuntu-latest label currently uses the Ubuntu 22.04 runner image.

**Comment by myoung34** [comment]
What software are you missing? Focal is still built nightly and on every release, it's just not tagged as latest anymore

**Comment by timnolte** [comment]
Specifically it's `skopeo` that is not included in the distribution. https://github.com/containers/skopeo

> The skopeo package is available in the official repositories for Ubuntu 20.10 and newer.

This is required in order to run the Dev Container Build and Run GitHub Action. https://github.com/marketplace/actions/dev-container-build-and-run-action

**Comment by myoung34** [comment]
Probably needs a bugfix to remove that check and just let it fail where its not available
As for skopeo on Focal: if its not available then it's not available. If you have  a PR to push an apt repository that would work that's likely the best path

**Comment by timnolte** [comment]
I think you are misunderstanding this request. The latest stable GitHub Runners use Ubuntu 22.04, this runner doesn't. If this runner was updated to be in parity with the GitHub Runners this wouldn't be a problem. Additionally, there is no apt repository that can be added to fix this. This application is already in the official Ubuntu repos but only starting with Ubuntu 20.10. And finally, I can't just ignore that missing package as it is required to even have my builds be functional.

**Comment by timnolte** [comment]
Also, noting that being required to install Go, setup new environment variables for Go, and building this package from source and install it causes the GitHub Runner runtime to be 10x that of a native GitHub Runner.

I guess if feature parity with the GitHub Runners is not the intent of this image I can fork it and build my own images for builds. I'd prefer not to have to do that but I understand if what I'm trying to accomplish is out of scope for the intent of this runner image. Thanks!

**Comment by myoung34** [comment]
Feature parity is important, if you have something that's upstream that isn't here, prs are welcome

I'm not concerned with matching their latest, however. If their latest is 22.04 then I provide `focal-latest`. Not everything here will be perfect, I can't provide 100% identical everything to something maintained by a full team on salary. I'm not missing parity here, that's simply a naming difference as I do in fact provide that version of Ubuntu. Using `latest` isn't best practice so it's not high on my list of things to match on

**Comment by timnolte** [comment]
Uh, I think you are missing the fact that Focal is not 22.04, Focal is 20.04. This runner is not the same Ubuntu version as the GitHub `latest`.

**Comment by timnolte** [comment]
OK, so I missed the fact that you do have a `ubuntu-jammy` tag. Sorry about the confusion, in my mind I was only going by what I saw in the base image `Dockerfile` and didn't even look at Docker Hub to see that there is a tag. I'll switch my containers to the correct tag. And of course you are totally right about using `lastest` with containers, I should have known better.

**Comment by timnolte** [comment]
@myoung34 I just noticed in the README that this issue is mentioned. https://github.com/myoung34/docker-github-actions-runner/issues/219

Is this actually still an outstanding issue?

**Comment by myoung34** [comment]
Unsure, I dont run these runners much at all, only for some niche side projects
