### ISSUE TITLE
Switch to Ubuntu 20.04 or 18.04

### ISSUE THREAD

**Issue by RyanW8** [myoung34/docker-github-actions-runner#35]
Can we please switch the base image to use either Ubuntu 18.04 or 20.04. As actions/setup-python only supports those two versions.

https://raw.githubusercontent.com/actions/python-versions/master/versions-manifest.json

**Comment by myoung34** [comment]
Ubuntu bionic (18.04) and eoan (19.10 aka latest for docker) are already a thing: https://hub.docker.com/repository/registry-1.docker.io/myoung34/github-runner-base/tags?page=1 (and https://github.com/myoung34/docker-github-actions-runner/blob/master/Dockerfile.base#L1)

as well as here https://hub.docker.com/repository/docker/myoung34/github-runner/tags?page=1

if youd like to submit a PR that works with focal (20.04) id be happy to test and merge, but I ran into issues when I attempted it

**Comment by myoung34** [comment]
If youd like to add support for focal id be OK merging it, but I ran into issues and dropped it since bionic and eoan are not EOL yet
