### ISSUE TITLE
Powershell support

### ISSUE THREAD

**Issue by adambajguz** [myoung34/docker-github-actions-runner#350]
Hello,
is PowerShell supported?

I have a job that uses PowerShell and it doesn't work.

```yml
 shell: pwsh
```

```bash
 Error: pwsh: command not found
```

**Comment by myoung34** [comment]
[Its supported upstream](https://github.com/actions/runner-images/blob/main/images/ubuntu/Ubuntu2204-Readme.md#powershell-tools)

If you issue a PR that works across all the image varieties Ill merge it

**Comment by adambajguz** [comment]
so the answer is no, what else is missing?

**Comment by myoung34** [comment]
The answer is sure, prs are welcome
