### ISSUE TITLE
Debian 12 `bookworm` runner

### ISSUE THREAD

**Issue by MattKobayashi** [myoung34/docker-github-actions-runner#365]
Would it be possible to create a Debian 12 `bookworm` version of this runner image?

**Comment by myoung34** [comment]
If it builds fine that shouldnt be an issue. 
It would most be additions to the files in .github/workflows/*.yaml

**Comment by MattKobayashi** [comment]
Thanks @myoung34, I've opened a PR for this: https://github.com/myoung34/docker-github-actions-runner/pull/366

**Comment by myoung34** [comment]
Resolved by #366

**Comment by myoung34** [comment]
Thanks!
