### ISSUE TITLE
turn off cute output

### ISSUE THREAD

**Issue by chlsmith** [myoung34/docker-github-actions-runner#367]
I would love an option to turn off all the cute output that goes to stdout.  We have this running in a container app and it's logged to Azure Log Analytics, which logs a record for every line of output.  I only really need errors or actual information, not the cute ASCII art.   

Is that possible already?  If not, please consider adding a flag to disable all of that.

**Comment by myoung34** [comment]
This is an ask for https://github.com/actions/runner/issues

I dont modify or maintain their runner, just package it as docker images
