### ISSUE TITLE
Http response code: NotFound

### ISSUE THREAD

**Issue by albertomiglionni** [myoung34/docker-github-actions-runner#377]
I ran the build from the docker image and when I go to run docker run this error is showing up in the logs:

docker logs github-runner-06

Http response code: NotFound from 'POST https://api.github.com/actions/runner-registration' (Request Id: 5351:12FEFB:FB0FE:1085C1:66AD3BA5)
{"message":"Not Found","documentation_url":"https://docs.github.com/rest","status":"404"}
Response status code does not indicate success: 404 (Not Found).
An error occurred: Not configured. Run config.(sh/cmd) to configure the runner.

**Comment by myoung34** [comment]
Sounds like an auth issue. Id ask upstream, but it doesn't seem related to the image here

**Comment by baglan1** [comment]
I encountered a similar issue. Resolved it by using a runner token and removing the ".git" at the end of the repo url.

**Comment by Aadniz** [comment]
For me it got solved by just generating a new runner token
