### ISSUE TITLE
mkdir: cannot create directory RUNNER_WORKDIR

### ISSUE THREAD

**Issue by pompushko** [myoung34/docker-github-actions-runner#378]
Hello

Used example for Ephemeral Runner

`Aug 13 16:17:04 docker[3698]: mkdir: cannot create directory ‘/tmp/runner/work’: No such file or directory`

Seems like it cannot create runner folder

**Comment by myoung34** [comment]
Can you elaborate on your setup, how its run/configured?

**Comment by pompushko** [comment]
> Can you elaborate on your setup, how its run/configured?

Example from your Wiki :)
But change to `/tmp/work` fix the issue.

**Comment by pirate** [comment]
is there any reason we cant just use the default `/home/runner/work` to match hosted Github Actions?
