### ISSUE TITLE
mount: /proc/sys/fs/binfmt_misc: permission denied

### ISSUE THREAD

**Issue by pompushko** [myoung34/docker-github-actions-runner#379]
I have custom arm build in Docker with **pguyot/arm-runner-action**. 
Locally and on GitHub cloud runners works fine with ubuntu-latest

Maybe Im doing something wrong? Thank you!

```
mount: /proc/sys/fs/binfmt_misc: permission denied.
update-binfmts: warning: Couldn't mount the binfmt_misc filesystem on /proc/sys/fs/binfmt_misc.
```

**Comment by myoung34** [comment]
What's your configuration? Environment vars, passing volumes etc

Also are you saying you're not using the runner I provide in this repo?

**Comment by myoung34** [comment]
I don't think this is an issue with the project here but I'm missing a lot of context for how the runner is configured

**Comment by pompushko** [comment]
I just take your wiki example :)

But seems like fixed:

```
ExecStart=/usr/bin/docker run --rm --privileged \
                              --env-file /etc/ephemeral-github-actions-runner.env \
                              -e RUNNER_NAME=%H \
                              -v /var/run/docker.sock:/var/run/docker.sock \
                              -v /dev:/dev \
                              --name %N \
                              myoung34/github-runner:ubuntu-jammy
```

Added option `--privileged`, new volume `-v /dev:/dev \` and distro is `ubuntu-jammy`
