### ISSUE TITLE
Question: where can I find the list of installed tools

### ISSUE THREAD

**Issue by DocMoebiuz** [myoung34/docker-github-actions-runner#380]
For the official github runner images there is a page where they list all installed packages and tools:
https://github.com/actions/runner-images/blob/main/images/ubuntu/Ubuntu2004-Readme.md

I was assuming that the tools would also be available for this container image version but I find that i.e. **AZ CLI** is missing.

Looks like the Github team has a json file which is considered for installing those tools:
https://github.com/actions/runner-images/blob/main/images/ubuntu/toolsets/toolset-2004.json

How did you go about these packages and tools? It looks like some of the packages are found in the Dockerfile.base

**Comment by myoung34** [comment]
They're installed adhoc at best, but any improvement to that is definitely a consideration

**Comment by vyadh** [comment]
I was considering doing a bit of refactoring of the Dockerfiles for similar reasons. What I'd actually like to do is turn things off to reduce the attack surface and reduce the need for patching.

Before I get carried away, how do you feel about me moving everything within the RUN in Dockerfiles.base into a dedicated script and then tidying it up a bit? The downside being that it would need to be copied into the image first, but it seems like a small price for easier maintainability? 

Once that's done, we could have a simple flags file of what to install, and the package list would be derived from that. Plus other useful configuration like user and group IDs.

If we did that, do we need two Dockerfiles or can we just have the one?

I'll note that while I can do testing on the things I use, it's not just, and I'm sure I might break things. Short of writing a test suite, how can we validate it?

**Comment by myoung34** [comment]
I'm ok with a script and a manifest of sorts to run

It will still always be two dockerfiiles though, one for base and one to build off of when the version bumps for time to build reasons 

It also means people can provide their own base and lay the smaller dockerfile on it for a FROM

I'm also ok with a test to validate , it's been on my to-do for as long as Ive maintained this

**Comment by DocMoebiuz** [comment]
Why do we have to recreate the wheel if the install scripts and config logic is already available https://github.com/actions/runner-images/blob/main/images/ubuntu/scripts/build/Install-Toolset.ps1

Ideally we could reuse those.

**Comment by vyadh** [comment]
I was mainly doing just a bit of refactoring of what is there to make it easier for me to create a minimal image downstream as I'd rather use other container images for tool specific work. Using the VM tool installs sounds neat though, and presumably can be done without needing PowerShell installed looking at those install scripts. Not sure I'll be able to go that far, but maybe what I'm doing will make that slightly easier to accomplish.

**Comment by vyadh** [comment]
Okay, I've probably gone as far as I plan to go with my refactoring for now. While it doesn't really resolve this issue, the refactoring I've done does make it much easier to see what's installed if you look in the new [tools.sh](https://github.com/vyadh/docker-github-actions-runner/blob/install-scripts/build/tools.sh#L102-L112) and [install_base.sh](https://github.com/vyadh/docker-github-actions-runner/blob/install-scripts/build/install_base.sh#L13) scripts with hand-cranked installs and `apt` installs respectively.

More related to this issue, I looked at the suggested GitHub scripts for installing tools. I didn't look at them extensively, but I noted that some are specific to the AWS VMs being used. Specifically the Docker one also installs a AWS credential helper. I'm going to assume that won't work and will require hacks to work around. That got me thinking about alternatives, so I had a play with Docker and [Nix](https://nix.dev). The nice thing about this approach is that it kept all the tools to install in the same place and it's far less likely to need hand-cranked per-tool install scripts and a much faster build. You can take a look at that [here](https://github.com/vyadh/container-tools) and specifically [the "flake" where the tools are declared](https://github.com/vyadh/container-tools/blob/main/flake.nix#L18-L21). Most of the tools used in this GitHub Runner image are supported.

I can do further refactoring to introduce that here. However, it doesn't really work for my purposes because the Nix "flake" functionality is experimental, so I'd personally not be happy to rely on it. Given that and the surrounding complexity it introduces, it doesn't seem worth it.

**Comment by myoung34** [comment]
Now that there is a `build/*.sh` dir it could be possible to build off of the upstream .json file by parsing it and figuring out how to make sure it handles nuances there

I've added basic tests, so as long as those last I'd be willing to entertain attempts

**Comment by vyadh** [comment]
So are you thinking of something like:

```json
{
  "apt": ["python3", "nodejs"],
  "script": ["aws-cli", "powershell"]
}
```

And the build script would go off and construct the needed commands to install what is specified?

FWIW, my first attempt was to try to put tools into categories, see [here](https://github.com/vyadh/docker-github-actions-runner/blob/tool-categories/installed_tools.sh) but it ended up needlessly overcomplicated. I suppose with a json file the tools could be in more clearly defined categories and the parsing just ignores that structure. The advantage being somewhat self-documenting, and perhaps not too more complicated to implement. For example:

```json
[
  {
    "category": "python",
    "source": "apt",
    "packages": ["python3", "python3-pip", "python3-setuptools", "python3-venv"]
  },
  ...
]
```

The actual `apt install` being an aggregate of all packages where source is `apt`, and something similar for script-based tools by `aws-cli`. Going back to the suggestion by @DocMoebiuz, we could add another source type to pull in and run the scripts provided by GitHub for their VM, which users can then specify via the right naming. Meaning, less need to implement any GitHub-supported tool that people might want in this repo.

**Comment by vyadh** [comment]
FWIW, this was fairly easy to throw together. See [diff here](https://github.com/vyadh/docker-github-actions-runner/pull/1/files).

This does user/group ids, apt installs and script-based installs from a `config.json` file. No GitHub VM runner-sourced installs yet though.

**Comment by DocMoebiuz** [comment]
> So are you thinking of something like:
> 
> ```json
> {
>   "apt": ["python3", "nodejs"],
>   "script": ["aws-cli", "powershell"]
> }
> ```
> 
> And the build script would go off and construct the needed commands to install what is specified?
> 
> FWIW, my first attempt was to try to put tools into categories, see [here](https://github.com/vyadh/docker-github-actions-runner/blob/tool-categories/installed_tools.sh) but it ended up needlessly overcomplicated. I suppose with a json file the tools could be in more clearly defined categories and the parsing just ignores that structure. The advantage being somewhat self-documenting, and perhaps not too more complicated to implement. For example:
> 
> ```json
> [
>   {
>     "category": "python",
>     "source": "apt",
>     "packages": ["python3", "python3-pip", "python3-setuptools", "python3-venv"]
>   },
>   ...
> ]
> ```
> 
> The actual `apt install` being an aggregate of all packages where source is `apt`, and something similar for script-based tools by `aws-cli`. Going back to the suggestion by @DocMoebiuz, we could add another source type to pull in and run the scripts provided by GitHub for their VM, which users can then specify via the right naming. Meaning, less need to implement any GitHub-supported tool that people might want in this repo.

i like the idea with providing a bit more info about the installed packages while keeping the set of attributes small that actually matter. 

`description` might be a sensible attribute too

so all in all:
`category` or `label` - to have a speaking identifier
`description` - as an optional field for more explanations 
`source` - the tool to be used
`packages` - an array of stuff

for the last two attributes it could also be simply `command` which would allow for a lot of flexibility

**Comment by vyadh** [comment]
Good idea. I'll add `description` another time (going to bed!). Obviously that won't change the implementation but I mean to the existing config and docs.

The `command` idea sounds interesting. How would you envision that to work? Literally the command to execute or more like a tiny DSL?

**Comment by DocMoebiuz** [comment]
i thought the plain command would give most flexibility instead of having to create different source types and then package might not make sense but only for apt or npm but for a different tool it would be a simple parameter list 

Hence command would be more universal

**Comment by myoung34** [comment]
Id rather support the [upstream json](https://github.com/actions/runner-images/blob/main/images/ubuntu/toolsets/toolset-2004.json) directly so that I can just point to that at build time and have 1:1 vs maintaining a copy

Im up for a different one, but to make things simpler:

* this repo currently only supports buildling ubuntu/debian on amd64 + arm64
* this repo is already not 1:1

Id rather just parse the upstream `toolset-{version}` per matrix directly and do what it can even if not everything perfectly.

**Comment by vyadh** [comment]
Ah, I get it. I'll have a look at it. Perhaps it can be an iteration to what I've done already. First glance says there are are a fairly substantial number of tools in those upstream images, including multiple versions of tools. Would we want all of that in this image?

**Comment by DocMoebiuz** [comment]
my initial intention was only to know what is installed already, we might be derailing this totally (even though it's cool) 😎

**Comment by vyadh** [comment]
I've had a better look at how the upstream toolset json works. I think it would be simple enough to grab the basic list of apt packages to install. Beyond that, things seem to get a bit more difficult. There is a whole set of rules and configuration that this json file drives, which determines what actually gets installed. Re-implementing a form of that logic seems like a lot of work (and not very interesting, haha). Pulling down the scripts from that repo might be a better approach, or even copy them and modify where required (if licenses allow). However, even that would take a while to unpick.

So, some questions for you @myoung34 
(1) How far do you want to go down that route?
(2) Would we look to re-implement, download, or tactically copy the GitHub scripts?
(3) Can we approach this incrementally? I can't guarantee I'll maintain the motivation to finish anything I start ;) I'll strip it down to the bare bones for my own usages anyway.

**Comment by myoung34** [comment]
1) Unsure, i guess "it depends" on actual complexity
2) They are largely boring [here](https://github.com/actions/runner-images/tree/c7adf5d533a9ee2cbe4ec1e954b5b73abff6e9a3/images/windows/scripts/build) . They call `Get-ToolsetContent` and do abunch of installs in those
3) 100% a fan of increments, i dont usually enjoy boiling the ocean

**Comment by vyadh** [comment]
Thanks for the clarifications. So in terms of the first increment, the PR I raised #393 gets us going in the right direction, if not the strategic format yet. Are you happy to merge that?

**Comment by vyadh** [comment]
I thought it would be interesting to see how far I could get trying to use the actual GitHub Runner VM install scripts to work in a container. It's a complete hack and I couldn't get it working for everything, but the result is [here](https://github.com/vyadh/github-actions-image/blob/master/Dockerfile).

It resulted in a two hour build and 40 GB container image 🤣

**Comment by myoung34** [comment]
https://github.com/myoung34/docker-github-actions-runner/wiki/Usage#modifications

and https://github.com/myoung34/docker-github-actions-runner/blob/master/build/config.json
