### ISSUE TITLE
Isnt this Docker out of Docker?

### ISSUE THREAD

**Issue by DavidJakszta** [myoung34/docker-github-actions-runner#381]
In the Per-Repo Runner exmaple on the [wiki](https://github.com/myoung34/docker-github-actions-runner/wiki/Usage) your bind mount   -v /var/run/docker.sock:/var/run/docker.sock   which means you dont use docker inside of docker but mount the outer docker daemon inside the container. Is this not mandatory or am i missing something? This seems like Docker out of Docker for me

**Comment by myoung34** [comment]
That is how docker in docker works, but that isn't supported with actions upstream so you can skip that, it's not needed

**Comment by DavidJakszta** [comment]
What do you mean it's not supported by actions upstream? I just want to self-host a GHA with docker in docker (No socket mounting)

**Comment by myoung34** [comment]
The readme links to the upstream issue. Docker is installed inside the image
