### ISSUE TITLE
Environment Variables for Runner Configuration Leaking to Workflows

### ISSUE THREAD

**Issue by yamoyamoto** [myoung34/docker-github-actions-runner#383]
As documented in the [README.md](https://github.com/myoung34/docker-github-actions-runner?tab=readme-ov-file#environment-variables), runner configuration can be set using environment variables passed to the container. However, we've discovered that these configuration variables are unintentionally accessible within the workflows themselves.

Our organization encountered a problem where environment variables that should not be present in workflows (beyond the [default environment variables](https://docs.github.com/en/actions/writing-workflows/choosing-what-your-workflow-does/store-information-in-variables#default-environment-variables)) were leaking into the workflow context, causing unintended behavior.

While we've implemented a workaround for this issue in our organization, we would greatly appreciate if this could be addressed upstream as well.

### Dockerfile

```Dockerfile
FROM ghcr.io/myoung34/docker-github-actions-runner:2.319.1-ubuntu-jammy

...

COPY run.sh /
RUN chmod +x /run.sh

COPY pre-start-service.sh /
RUN chmod +x /pre-start-service.sh

ENTRYPOINT ["/run.sh"]
CMD ["./bin/Runner.Listener", "run", "--startuptype", "service"]
```

### run.sh

```bash
# Execute entrypoint.sh without starting the service, allowing us to unset environment variables after configuration but before runner startup
/entrypoint.sh true

# Execute pre-start operations
source /pre-start-service.sh

# Start the runner service
# Assuming RUN_AS_ROOT=false: https://github.com/myoung34/docker-github-actions-runner/blob/eb29a1af8cef6e75e9ea673beb78b090c646e45c/entrypoint.sh#L208
exec /usr/sbin/gosu runner "$@"
```

### pre-start-service.sh

```bash
# Unset environment variables used for myoung34/docker-github-actions-runner configuration
# to prevent unintended access from workflows
# Note: This unset operation must occur before the runner service starts
unset EPHEMERAL
unset DISABLE_AUTO_UPDATE
unset RANDOM_RUNNER_SUFFIX
unset ENTERPRISE_NAME
unset RUNNER_SCOPE
unset LABELS
unset RUNNER_GROUP
unset RUNNER_NAME_PREFIX
unset RUN_AS_ROOT
unset RUNNER_WORKDIR
unset APP_LOGIN
unset RUNNER_ALLOW_RUNASROOT
# Additional variables as needed...
```

## Ideal Solution

We propose implementing a mechanism to unset the configuration environment variables after runner setup (e.g., execution of config.sh) but before the runner is started (`./bin/Runner.Listener run --startuptype service`). This would ensure that these variables are available for configuration but not leaked to the workflow execution environment.

**Comment by myoung34** [comment]
What variables caused issues? Im not against unsetting some by design, but most of these are custom and `_` prefixed so "leakage" is of no risk such as `_EPHEMERAL` etc so Im not sure theres any need to go so far as to blindly unset every one of them.

**Comment by yamoyamoto** [comment]
> What variables caused issues?

It's more of an overall issue rather than specific environment variables causing problems.

For instance, in our organization, we were using `RUNNER_SCOPE` to override default deployment settings of an application in a repository for local development. However, we expected default settings in CI and thus didn't register it in the repository's Variables. Despite this, the issue caused unintended setting overrides.

Our organization is fairly large with active use of self-hosted runners, so we'd like to minimize such behaviors that deviate from official documentation (like `RUNNER_SCOPE` not being listed in the [default environment variables](https://docs.github.com/en/actions/writing-workflows/choosing-what-your-workflow-does/store-information-in-variables#default-environment-variables)).
What are your thoughts on this?

> _ prefixed so "leakage" is of no risk such as _EPHEMERAL etc so Im not sure theres any need to go so far as to blindly unset every one of them.

I agree that variables prefixed with `_` leaking to the Workflow side isn't problematic. However, these are local variables in [entrypoint.sh](https://github.com/myoung34/docker-github-actions-runner/blob/master/entrypoint.sh), so I think they don't leak to the actions/runner process or the Workflow side.

But, the variables without `_` prefix [introduced in the README](https://github.com/myoung34/docker-github-actions-runner?tab=readme-ov-file#environment-variables) are intended to be exported as container process environment variables. As a result, wouldn't these leak to the Workflow side?

In fact, as mentioned in https://github.com/myoung34/docker-github-actions-runner/pull/384, currently if `REPO_URL` is used as a configuration value for myoung34/docker-github-actions-runner, it leaks to the Workflow side.
