### ISSUE TITLE
An error occurred: The signature is not valid.

### ISSUE THREAD

**Issue by davetapley** [myoung34/docker-github-actions-runner#400]
Runner has been working fine for years, now suddenly failing shortly after `Running job: ...` with:

```
An error occurred: The signature is not valid.
```

I'm on latest:
```
Current runner version: '2.319.1'
```

Open ticket with support too, nothing on https://www.githubstatus.com/.

**Comment by davetapley** [comment]
One mention here, could be intermittent, but is 100% for me presently:

https://github.com/actions/actions-runner-controller/issues/3006#issuecomment-2052238126

**Comment by myoung34** [comment]
```
Runner reusage is disabled
Obtaining the token of the runner
Configuring
--------------------------------------------------------------------------------
|        ____ _ _   _   _       _          _        _   _                      |
|       / ___(_) |_| | | |_   _| |__      / \   ___| |_(_) ___  _ __  ___      |
|      | |  _| | __| |_| | | | | '_ \    / _ \ / __| __| |/ _ \| '_ \/ __|     |
|      | |_| | | |_|  _  | |_| | |_) |  / ___ \ (__| |_| | (_) | | | \__ \     |
|       \____|_|\__|_| |_|\__,_|_.__/  /_/   \_\___|\__|_|\___/|_| |_|___/     |
|                                                                              |
|                       Self-hosted runner registration                        |
|                                                                              |
--------------------------------------------------------------------------------
# Authentication
√ Connected to GitHub
# Runner Registration
√ Runner successfully added
√ Runner connection is good
# Runner settings
√ Settings Saved.
√ Connected to GitHub
Current runner version: '2.319.1'
2024-10-01 12:51:41Z: Listening for Jobs
```

So the runner itself is fine and the upstream actions service API is healthy

From [here](https://github.com/actions/runner/issues/2944) it looks like there may be other factors, but since this issue is likely related to the actual runner software itself I'd recommend you move the issue there

**Comment by davetapley** [comment]
@myoung34 yep, and seems intermittent since it's now working again with no intervention 🤷🏻 

Thanks for the great project! 🙏🏻

**Comment by davetapley** [comment]
This occurred again, and with a different error message.

I'll post that error and my support ticket message here in case others are impacted and find it via search, hope that's okay.

I won't be offended if you unsubscribe to avoid noise @myoung34 😁 

---


New error:
```
2024-10-02 16:46:04Z: Runner connect error: The signature is not valid.. Retrying until reconnected.
An error occurred: Access denied. System:ServiceIdentity;DDDDDDDD-DDDD-DDDD-DDDD-DDDDDDDDDDDD needs View permissions to perform the action.
```

My support ticket:

I'm using https://github.com/myoung34/docker-github-actions-runner

It has been working great for several years, but in the last few days the runner is crashing with `An error occurred: The signature is not valid`. when picking up a job.

The Actions UI says `This job failed`, and under **Annotations** it says:

```
The self-hosted runner: alert lost communication with the server. Verify the machine is running and has a healthy network connection.
Anything in your workflow that terminates the runner process, starves it for CPU/Memory, or blocks its network access can cause this error.
```

It's intermittent, and doesn't appear related to any one specific repo, and occurring approx. 20% of all job runs. Sometimes we can restart a run and it will work with no changes.

I opened an issue [here](https://github.com/myoung34/docker-github-actions-runner/issues/400), but both I and the maintainer are fairly sure it's an upstream issue.
