### ISSUE TITLE
"It is known that environment variables are not safe from exfiltration."

### ISSUE THREAD

**Issue by joeyparrish** [myoung34/docker-github-actions-runner#401]
What do you mean in the README when you say this?

> It is known that environment variables are not safe from exfiltration.

Is it trivial to exfiltrate the tokens?  I thought we unset these.  Or is it just any other environment variables made available inside the container?

**Comment by myoung34** [comment]
_TOKEN, ACCESS_TOKEN are not masked as they are part of the startup process, but most people tend to inject other env vars into runners:

```
$ k -n actions-runner exec -it pod/actions-runner-879df584-4xk6f env | grep -i TOKEN
VAULT_TOKEN=hvs.redact
ACCESS_TOKEN=ghp_redact
CLOUDFLARE_API_TOKEN=Nvgyre-redact
```

**Comment by myoung34** [comment]
Some various methods that could exfil those: https://i.blackhat.com/BH-US-24/Presentations/US24-Khan-Self-Hosted-GitHub-CICD-Runners-Continuous-Integration-Continuous-Destruction.pdf including a link to my [blog post](https://markyoung.us/post/zuckerpunch/) where I did similar

**Comment by joeyparrish** [comment]
That is fascinating stuff.  Thanks!
