### ISSUE TITLE
Missing NPM

### ISSUE THREAD

**Issue by Rickyc81** [myoung34/docker-github-actions-runner#405]
Hi, i've a problem with the container, node is installed in /bin but npm is missing

![image](https://github.com/user-attachments/assets/aaa29158-7ce6-41a1-8311-0230a4282d55)

however, creating the workflow using the github runner, and not the self hosted one, it works.. should I install it manually or modify the dockerfile?

Thanks!

**Comment by myoung34** [comment]
This should be as easy as adding `npm` [after this line](https://github.com/myoung34/docker-github-actions-runner/blob/master/build/config.json#L85)

**Comment by Rickyc81** [comment]
thanks! I created an image starting from yours with some extra things already installed that I needed.
Thanks a lot!
