### ISSUE TITLE
Image as Non-Root

### ISSUE THREAD

**Issue by thorker** [myoung34/docker-github-actions-runner#41]
It is possible to run this image without root?

As a workaround I changed the access control of the folders I have to access by extending your image.

**Comment by myoung34** [comment]
Sure, its usually as easy as: 

```
RUN useradd -ms /bin/bash newuser
USER newuser
``` 

assuming that you dont need to control the UID (probably should) and that it doesnt need sudo access for some things (it probably does)

if you submit a PR id be happy to review and give feedback
