### ISSUE TITLE
Updated Docker Compose example for the wiki

### ISSUE THREAD

**Issue by neoKushan** [myoung34/docker-github-actions-runner#410]
Hi,

I've been setting up a github runner using this project for my own personal use. During this, I encountered a few issues that required a bit of extra digging and debugging to resolve so I would like to propose a change to the documentation for docker compose, specifically the example compose given. 

Here's my suggested update:

```
version: '2.3'
services:
  worker:
    image: myoung34/github-runner:latest
    environment:
      REPO_URL: https://github.com/example/repo
      RUNNER_NAME: example-name
      RUNNER_TOKEN: someGithubTokenHere 
      RUNNER_WORKDIR: /tmp/runner/work
      CONFIGURED_ACTIONS_RUNNER_FILES_DIR: /runner/data # Required for persistence
      # RUNNER_GROUP: my-group
      RUNNER_SCOPE: 'repo'
      LABELS: linux,x64,gpu
    security_opt:
      # needed on SELinux systems to allow docker container to manage other docker containers
      - label:disable
    volumes:
      - '/var/run/docker.sock:/var/run/docker.sock'
      - '/runner/data:/runner/data' # required for persistence
      - '/tmp/runner:/tmp/runner'
      # note: a quirk of docker-in-docker is that this path
      # needs to be the same path on host and inside the container,
      # docker mgmt cmds run outside of docker but expect the paths from within
```

These are the changes I think should be made and why:

- Add `CONFIGURED_ACTIONS_RUNNER_FILES_DIR` - this is essential for persistence; I don't believe most people using compose are expecting to have to re-register their agent every time, the usage of compose implies some level of persistence is probably expected. I have used the path `/runner/data` but I'm not precious about this particular path at all, it's just an example
- Added Volume mount for that runner data
- Comment out `RUNNER_GROUP` by default - this is an Enterprise only feature and it'll fail if it's anything other than "Default".

My overall rationale for these changes is that anyone spinning up a runner via Docker compose is far more likely to be a personal user (As opposed to Enterprise) looking to set up a persistent local runner. The idea is to make the compose file as copy and paste-able as possible without needing many changes, to help ensure people deploying via this method fall into the pit of success rather than fail at the first hurdle because they can't use groups, then have their runner fail a few days later when it restarts and can't register using the same key as previously.

**Comment by myoung34** [comment]
Updated, thanks!
