### ISSUE TITLE
Multiple Workers / scaling with Docker Compose

### ISSUE THREAD

**Issue by jonguenther** [myoung34/docker-github-actions-runner#411]
Hey all,

first off, thanks for the great docker util! Makes it much easier to use the GH runner.

In my repo I have jobs that run in parallel and take some time (think unit testing & e2e with matrix). Following the `Docker Compose` [example in the wiki](https://github.com/myoung34/docker-github-actions-runner/wiki/Usage#docker-compose), I noticed that only one worker is being created. I tried to use `deploy: replicated` but this lead to write conflicts among other things. 

My question now is, whether I should define multiple worker services in the compose file with different volumes, or if there is another solution that I could try to get multiple workers in a repo.

Thanks in advance for your help!

**Comment by vyadh** [comment]
I use --scale with Docker Compose, which a common set of host-mapped volumes, which works well for me. I had another look at the config and I don't see anything specific to make that work, but it is using a customised image. Where were you seeing write conflicts?
