### ISSUE TITLE
Scaling multiple Repos

### ISSUE THREAD

**Issue by dzenansoftic** [myoung34/docker-github-actions-runner#414]
Hello,

is the env var REPO_URL stricly bound to 1 repo or is there a possibility to create runners for multiple repos with one configuration?

**Comment by myoung34** [comment]
REPO_URL is for a single repo. You'd need to find a way to automate this or use an organization. My repo is less concerned with scaling and run-time usage, just that it provides a necessary mechanism for the runner software itself, however.
