### ISSUE TITLE
ACCESS_TOKEN on Per-Repo runners

### ISSUE THREAD

**Issue by fintechestenberg** [myoung34/docker-github-actions-runner#415]
When I setup this using access_token for auth on a per-repo runner, this error occurs; (wokrs fine with reunner _token, but that requires constant refreshing of the token, which is impractical.)

![image](https://github.com/user-attachments/assets/ff2c8296-9e3a-4e27-a92e-4a64931bb5c3)

I also tried to add the github username as an env to the container in addition without success,
But I guess this is only for actual orgs
ORG: myusername

My compose code,
```
version: '2.3'
services:
  upptimerunner:
    image: myoung34/github-runner:latest
    restart: always
    environment:
      REPO_URL: https://github.com/fintechestenberg/upptime
      RUNNER_NAME: upptime
      ACCESS_TOKEN: MYTOKEN
      RUNNER_WORKDIR: /tmp/runner/runner
      #RUNNER_GROUP: onprem
      RUNNER_SCOPE: 'repo'
      LABELS: linux,x64,upptime
    security_opt:
      # needed on SELinux systems to allow docker container to manage other docker containers
      - label:disable
    volumes:
      - '/var/run/docker.sock:/var/run/docker.sock'
      - '/tmp/runner:/tmp/runner'
      # note: a quirk of docker-in-docker is that this path
      # needs to be the same path on host and inside the container,
      # docker mgmt cmds run outside of docker but expect the paths from within
```

**Comment by myoung34** [comment]
Im unsure. Im using this here: https://github.com/myoung34/homelab/blob/main/k8s/prod/actions-runner/actions.yaml

That works and it runs successfully, as well as looks very similar to yours (per repo with an access token). My guess is something related to your access token permissions.

![image](https://github.com/user-attachments/assets/519e25e1-7939-422d-8130-35df1e8ae425)

**Comment by fintechestenberg** [comment]
You are indeed correct, sort of.
My token was correct, but turns our the checkout step in my acitons flow was using a diffrent token because reasons.
I'll close this, thanks for feedback :-)
