### ISSUE TITLE
Disk Space Full

### ISSUE THREAD

**Issue by dickermoshe** [myoung34/docker-github-actions-runner#418]
It seems that the build cache is filling up container and blocking future builds.
Filled up 10gb of space after 10 builds.

I spent hours setting up a s3 as cache, would be awesome if this worked out of the box.
Although with EPHEMERAL fix this

**Comment by myoung34** [comment]
This is better for upstream as this repo does not control the core features or behaviors. Looks like there are similar reports such as https://github.com/actions/runner/issues/2708
