### ISSUE TITLE
Runner for organization: 403 Forbidden

### ISSUE THREAD

**Issue by divlv** [myoung34/docker-github-actions-runner#43]
I've used `myoung34/docker-github-actions-runner` dockerized self-hosted runner for 6 months and everything was fine. 
Now, I'm trying to enable my GitHub self-hosted runner for my organization, but, no luck.
It keeps reporting 403 error:
```
curl: (22) The requested URL returned error: 403 Forbidden
Configuring

...SKIP...

# Authentication

Invalid configuration provided for token. Terminating unattended configuration.
.path=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/actions-runner
Starting Runner listener with startup type: service
Started listener process
Started running service
An error occurred: Not configured
Runner listener exited with error code 2
Runner listener exit with retryable error, re-launch runner in 5 seconds.
Starting Runner listener with startup type: service
Started listener process
An error occurred: Not configured
```
... and so on.

I found my organization name here:
![org](https://user-images.githubusercontent.com/3175772/89282310-048a7080-d654-11ea-849b-1e0477a0b285.png)

I've created a token with appropriate permissions (according to official GitHub documentation):
![permissions](https://user-images.githubusercontent.com/3175772/89282422-2be13d80-d654-11ea-88ee-f04bf215a665.png)

And this is a command I use to start:
```
docker run -e RUNNER_NAME_PREFIX="myrnr" \
-e ACCESS_TOKEN="116f109961bfd1a9a689a4fe1db25a0834a17e0f" \
-e ORG_RUNNER="true" \
-e ORG_NAME="MyOrgNameFrom1stScreenshot" \
-e RUNNER_WORKDIR="/tmp/github-runner" \
-v /var/run/docker.sock:/var/run/docker.sock \
-v /tmp/github-runner:/tmp/github-runner \
 myoung34/github-runner:latest
```

So... what I am doing wrong?

**Comment by myoung34** [comment]
I ran exactly the same snippet and it worked fine: 

![](https://i.imgur.com/q8WZ5QQ.png)

Its either a scope wrong on the token or the token somehow is no longer authorized (or the org changed settings)

**Comment by myoung34** [comment]
```
curl: (22) The requested URL returned error: 403 Forbidden
Configuring

...SKIP...
```

is interesting. in entrypoint the only `curl` is in `token.sh`, which runs:

```
RUNNER_TOKEN="$(curl -XPOST -fsSL \
  -H "${AUTH_HEADER}" \
  -H "${API_HEADER}" \
  "${_FULL_URL}" \
| jq -r '.token')"
```

which makes me suspect the org settings for the runnner. Make sure they match:

![](https://i.imgur.com/epgItCa.jpg)

My guess is that your user doesnt have privileges to generate a PAT that works for org level runners

**Comment by divlv** [comment]
Hmm... Not sure where can I check this? (where, indeed?)

My account was created and added to this organization by a _super-admin-far-far-away_ ;-)
Here's how my organization page looks like:

![myorg](https://user-images.githubusercontent.com/3175772/89302717-db79d800-d673-11ea-8774-438714c3453b.png)

Does it means - I cannot create the necessary PAT due to lack of privileges?..

**Comment by myoung34** [comment]
Im not sure to be honest, but you cant see Settings for the org (and mine works) so I have to assume its an auth setting thats not enabled for your user to the org, so the PAT you generated isnt scoped high enough to enable runners for the org.

The better choice here would be a service account added to the org for controlling runners

**Comment by myoung34** [comment]
I'm gonna close this for now, as there's nothing to be done from here.

If you find out what permissions are needed to generate PAT's for an org (to the user) and want to update the README, that might help others in the future, however.

**Comment by divlv** [comment]
Just to clarify: 
I've received new token from Organization admin (created with admin's account) and now - all working good!
(So, you was right regarding PAT scope.)
Thanks.

**Comment by myoung34** [comment]
@divlv if you can find out what scope was used that might be helpful to document in the README for others

**Comment by moeyashi** [comment]
@myoung34 Can I edit wiki for fine-grained PAT scope?

This is draft

---

##### Fine-grained tokens

###### repo scope

Should be able to call 

- https://docs.github.com/en/rest/actions/self-hosted-runners#create-a-registration-token-for-a-repository

Permissions

- administration: write
    https://docs.github.com/en/rest/overview/permissions-required-for-fine-grained-personal-access-tokens?apiVersion=2022-11-28#repository-permissions-for-administration

###### org scope

Should be able to call 

- https://docs.github.com/en/rest/actions/self-hosted-runners#create-a-registration-token-for-an-organization

Permissions

- self-hosted-runners: write
    https://docs.github.com/en/rest/overview/permissions-required-for-fine-grained-personal-access-tokens?apiVersion=2022-11-28#organization-permissions-for-self-hosted-runners

**Comment by kahlil29** [comment]
Thanks @moeyashi for noting this down. 
I had HTTP 403 errors with a Classic token using the permissions specified in the Wiki, but I got it to run with a fine-grained Access Token using the scope/permission combo you provided above
