### ISSUE TITLE
Support to register runner at enterprise account level

### ISSUE THREAD

**Issue by uwehdaub** [myoung34/docker-github-actions-runner#45]
Please support the new feature of having runners at enterprise account level:
https://github.blog/changelog/2020-08-05-github-actions-enterprise-runners-and-runner-groups

**Comment by myoung34** [comment]
I dont have an enterprise account to test with, but if you submit or scaffold what that PR would look like we can get something in

**Comment by uwehdaub** [comment]
This is the answer I expected. ;-)
Lets see when I find time to create a PR for it.

**Comment by myoung34** [comment]
If there's anything you're able to add to the docs or code I'm OK to work with it, but I'm going to close this in lieu of a PR
