### ISSUE TITLE
Docker health check

### ISSUE THREAD

**Issue by joshhsoj1902** [myoung34/docker-github-actions-runner#49]
Is there any way for the container to detect if it self is healthy?

I'm running my action runner in k8s pods, and it works fine for the most part, but sometimes the process seems to crash, and when that happens the auth logic doesn't seem to work and the pod ends up in an endless loop with this error:

```
Started listener process
An error occurred: Not configured
Runner listener exited with error code 2
Runner listener exit with retryable error, re-launch runner in 5 seconds.
Starting Runner listener with startup type: service
Started listener process
An error occurred: Not configured
Runner listener exited with error code 2
Runner listener exit with retryable error, re-launch runner in 5 seconds.
Starting Runner listener with startup type: service
Started listener process
An error occurred: Not configured
Runner listener exited with error code 2
Runner listener exit with retryable error, re-launch runner in 5 seconds.
Starting Runner listener with startup type: service
Started listener process
An error occurred: Not configured
Runner listener exited with error code 2
Runner listener exit with retryable error, re-launch runner in 5 seconds.
Starting Runner listener with startup type: service
Started listener process
An error occurred: Not configured
Runner listener exited with error code 2
Runner listener exit with retryable error, re-launch runner in 5 seconds.
Starting Runner listener with startup type: service
Started listener process
An error occurred: Not configured
Runner listener exited with error code 2
Runner listener exit with retryable error, re-launch runner in 5 seconds.
``` 

I was trying to find if there was anything I could use to create a healthcheck, but the only thing I could find was logs... and parsing logs as part of a healthcheck is a last resort for me.

Do you guys have any ideas?

**Comment by myoung34** [comment]
I thought about this and Im not sure there can be one baked in.

Example: the process isnt exiting, so PID1 is fine, and HEALTHCHECK for something like `ps` will see that its running, not throttling

Your best bet is an external health checker that looks at the runners via the Github API and looks for runners that arent active

**Comment by joshhsoj1902** [comment]
oh interesting, I hadn't considered trying to call the API... hmm, If I have time I'll see if I can throw something together. If I get something working that I'm not ashamed of I'll let you know :)

**Comment by joshhsoj1902** [comment]
Feel free to close this if you don't think it's worth having open

**Comment by myoung34** [comment]
Ill close it but if you can think of anything: im all ears

I just cant imagine a way to gather health from inside the container if the PID1 process is chugging along and not exiting on runner listener exit

**Comment by joshhsoj1902** [comment]
@myoung34 I'm going to try running this for a little bit and see if it is able to detect an unhealthy runner

https://github.com/joshhsoj1902/docker-github-actions-runner/blob/master/healthy.sh

**Comment by dcmoore-gd** [comment]
@joshhsoj1902 did you end up using ^ or come up with some other solution?  Thanks!

**Comment by joshhsoj1902** [comment]
@dcmoore-gd I used my fork for a few months. But I've since went back to running github actions outside of docker/k8s :(

**Comment by dcmoore-gd** [comment]
Gotcha, thanks for the reply @joshhsoj1902!  BTW right after I posted my comment above I finally found this which might help too:  https://github.com/actions-runner-controller/actions-runner-controller#runner-coming-up-before-network-available

If not, planning to try your script or something along those lines.  Thanks for posting that!
