### ISSUE TITLE
Docker-in-docker-in-docker

### ISSUE THREAD

**Issue by splitice** [myoung34/docker-github-actions-runner#50]
I understand this is a little outside scope but is there any chance you could provide an example of (successfully) executing a docker container from within a (your) self-hosted docker runner.

I appreciate your positive response 👍

**Comment by myoung34** [comment]
were you able to figure it out? It should work the same as if not hosted

**Comment by splitice** [comment]
Yes, it was just a permission error on the docker socket.

I'm not sure if it's the same with hosted.
