### ISSUE TITLE
Container feature is not supported when runner is already running inside container.

### ISSUE THREAD

**Issue by ScottPierce** [myoung34/docker-github-actions-runner#61]
I already saw https://github.com/myoung34/docker-github-actions-runner/issues/42

My question is - **how is everyone not running into this?** It seems like this is a restriction for all OS?
https://github.com/actions/runner/blob/f9b5d626c5486d1f02b3bd45879f61834b7aeecc/src/Runner.Worker/ContainerOperationProvider.cs#L57-L70

The docker runner seems pointless if we can't launch other containers from it. Can someone else describe how they have this working so that I can emulate it?

**Comment by myoung34** [comment]
> how is everyone not running into this?

Not every workflow kicks off docker

To be honest your best bet is to try and make progress on getting upstream support for https://github.com/actions/runner/issues/406

**Comment by BretFisher** [comment]
Yep, same issue. Tried to add an [Actions Service to a job](https://docs.github.com/en/actions/guides/about-service-containers), and got this error. It checks cgroups, so I don't see a hacky way around it (other then not using Job Services).

I'll submit a PR to highlight this limitation at the top of the readme so someone doesn't spend time trying to implement this container image, only to find out later it limits GHA functionality.

**Comment by myoung34** [comment]
@BretFisher It's documented [here](https://github.com/myoung34/docker-github-actions-runner#docker-support)

**Comment by BretFisher** [comment]
Yea, but I read that as saying "docker isn't officially supported by GitHub as a way to run runners", not "using this image will limit GHA functionality" so hopefully that clarification helped. Thanks for all you do.
