### ISSUE TITLE
Docker in docker actions - workspace files are not found - SOLVED

### ISSUE THREAD

**Issue by ameoba32** [myoung34/docker-github-actions-runner#7]
While running other actions that are inside docker containers I faced issue with files not found, like workfolder is empty.

This is because github container runs other action container (docker-in-docker) with this mount
```-v "/_work/_temp/_github_workflow":"/github/workflow"```
and since this is handled by docker daemon on host system, path "/_work" does not exists there.

I was able to overcome this issue by specifying same work folder on all containers like in this command:
```
  docker run -d --restart always --name github-runner \
  -e REPO_URL="https://github.com/***" \
  -e RUNNER_TOKEN="***" \
  -e RUNNER_WORKDIR="/tmp/github-runner" \
  -v /var/run/docker.sock:/var/run/docker.sock \
  -v /tmp/github-runner:/tmp/github-runner \
  myoung34/github-runner:latest
```

**Comment by myoung34** [comment]
Thanks, Ill use this to update the docs unless you can think of a more permanent fix!

**Comment by myoung34** [comment]
@ameoba32 https://github.com/myoung34/docker-github-actions-runner/commit/2f3b19dbcba5b6da0389746aa188486e041f2468

Thanks 🎉
