### ISSUE TITLE
Question: token scope

### ISSUE THREAD

**Issue by damacus** [myoung34/docker-github-actions-runner#70]
Hey, thanks for all the awesome work maintaining this project. 

We're running this runner in two orgs, but today we started questioning the scopes of the runner. 

I've left question marks where I'm confused as to why we need 

```text
repo (all) 👍 
admin:org (all) (mandatory for organization-wide runner) ❓ 
admin:public_key - read:public_key ❓ 
admin:repo_hook - read:repo_hook ❓ 
admin:org_hook ❓ 
notifications ❓ 
workflow 👍 
```

As a result I dropped the permissions down to: 

```text
repo (all)
workflow
```

It still:
-  managed to register at the org level
- picked up jobs
- ran the jobs with the correct Docker/AWS permissions. 

Is there anything I'm missing when testing reducing the scope here?

**Comment by xoen** [comment]
FWIW: I was looking at the [GitHub API documentation related to Self-Hosted runners](https://developer.github.com/v3/actions/self-hosted-runners/) and AFAICT it does **not** mention the following scopes:
- `admin:public_key`
- `admin:repo_hook`
- `admin:org_hook`
- `notifications`

Wouldn't that mean that these are not required by the runner then?

**Comment by myoung34** [comment]
The documentation for the scopes was provided by a contributor. If you can get it working with less then that's great and could throw up a pr to update it

**Comment by damacus** [comment]
Cool. I've also asked GitHub Support. I'll let you know what they come back with 👍

**Comment by damacus** [comment]
## From support 

Your token will need `admin:org` permissions at a minimum to both [create a self hosted runner group for an organization](https://docs.github.com/en/free-pro-team@latest/rest/reference/actions#create-a-self-hosted-runner-group-for-an-organization), and to [create a registration token for an organization](https://docs.github.com/en/enterprise-server@2.22/rest/reference/actions#create-a-registration-token-for-an-organization). The latter of which will return the token needed to configure your self hosted runner after its installation.

**Comment by myoung34** [comment]
I'm going to close only in lieu of a PR. if there's something you'd like to add to the README I'm ok to merge a PR, but until then there's not much to gleam from here
