### ISSUE TITLE
Size of image?

### ISSUE THREAD

**Issue by gaggle** [myoung34/docker-github-actions-runner#73]
First of all, thank you for the image! Makes it wonderfully simple to get started.

May I ask if you'd like to optimise the image size, as it currently weights in at 1.27GB? A "pull-requests welcomed" answer is fine, just looking to orient myself before I try to dive in in case the size is actually a considered or solved topic already.

**Comment by myoung34** [comment]
It's optimized sightly but if you have any ideas feel free to open any pr's

I likely won't be willing to swap Ubuntu for alpine but I'm willing to allow them in addition to Ubuntu
