### ISSUE TITLE
Size of overlay2 folder

### ISSUE THREAD

**Issue by ModdyLP** [myoung34/docker-github-actions-runner#79]
Hello,

i have an issue with the overlay2 folder. There is a folder that contains the data of the image from your Dockerfile but it causes on my server 17 GB of disk usage. Can you explain me that? I`m not an expert in docker so i dont know how to reduce it. Can i simple delete this folder? I mean the image itself is only 2.1 GB in Size why does it use so much more on the disk?

Thank you for the great work and the really good possibility to run an action runner inside docker. 

Kind Regards

**Comment by myoung34** [comment]
You'll need to look up how to clean volumes. See here https://docs.docker.com/engine/reference/commandline/volume_prune/

Closing as this is unrelated to the project as a whole
