### ISSUE TITLE
focal image

### ISSUE THREAD

**Issue by davidkarlsen** [myoung34/docker-github-actions-runner#86]
Github standard runners default to focal (20.04) - maybe this image should provide that flavour too?

**Comment by myoung34** [comment]
Focal is the default: https://github.com/myoung34/docker-github-actions-runner/blob/master/Dockerfile.base#L1

**Comment by davidkarlsen** [comment]
Doh - I missed it because there was no specific tag for it at https://hub.docker.com/r/myoung34/github-runner/tags
