### ISSUE TITLE
Error with various actions; Missing GITHUB_EVENT_PATH /github/workflow/event.json

### ISSUE THREAD

**Issue by onyxhat** [myoung34/docker-github-actions-runner#90]
I'm seeing the following error in several actions we pull in regularly - they work fine with GitHub's runners, but not while using this image as a self-hosted runner. I've verified that the `/github/workflow` folder exists, but whatever process is supposed to be adding the event.json event data doesn't appear to be happening.

```
GITHUB_EVENT_PATH /github/workflow/event.json does not exist
```

The resolution that others seem to be reaching with similar issues is to just run the actions-runner directly on the VM, instead of in the container, but I'd love to keep running as a container.

I see this issue specifically with the following actions:

- wagoid/commitlint-github-action
- FranzDiebold/github-env-vars-action

I suspect more would be affected, but those are the ones I know for certain have an issue.

**Comment by myoung34** [comment]
I'm not sure. Whatever this is its happening from the runner code itself and not from something container specific: https://github.com/myoung34/docker-github-actions-runner/blob/master/install_actions.sh .

You might open an issue at https://github.com/actions/runner but theres nothing I can do in this repo specifically to fix it. This project simply installs their tarball into the container

If you get feedback from upstream with a fix that can be made here I'd be happy to merge it though, so feel free to circle back
