### ISSUE TITLE
Can you get the latest version number of runner through the GitHub API?

### ISSUE THREAD

**Issue by bigfacewo** [myoung34/docker-github-actions-runner#92]
So we can use the latest version every time we run it.

Just like this:
```
RUN GITHUB_RUNNER_VERSION=$(curl --silent "https://api.github.com/repos/actions/runner/releases/latest" | jq -r '.tag_name[1:]') \
    && curl -Ls https://github.com/actions/runner/releases/download/v${GITHUB_RUNNER_VERSION}/actions-runner-linux-x64-${GITHUB_RUNNER_VERSION}.tar.gz | tar xz \
    && sudo ./bin/installdependencies.sh
```

https://github.com/SanderKnape/github-runner/blob/master/Dockerfile

**Comment by myoung34** [comment]
Its in the Dockerfile: https://github.com/myoung34/docker-github-actions-runner/blob/master/Dockerfile#L8

If youd like it to be printed out at start up that would be a good feature request for the upstream app: https://github.com/actions/runner/issues

If you dont care about the version you can simply use `myoung34/github-runner:latest` or pin to a specific version: `myoung34/github-runner:2.277.1-ubuntu-bionic` which will tell you what version youre at and the logs will tell you what version its trying to update as

**Comment by bigfacewo** [comment]
I got the wrong concept, thank you.
