### ISSUE TITLE
conditional unregistration?

### ISSUE THREAD

**Issue by davidkarlsen** [myoung34/docker-github-actions-runner#94]
Hi - I have a similar image in https://github.com/evryfs/github-actions-runner, but think I could maybe drop it in favour of this one.
I manage the pods with https://github.com/evryfs/github-actions-runner-operator
The operator handles unregistration, and hence I'd like to avoid the runner pod to attempt to do this itself in https://github.com/myoung34/docker-github-actions-runner/blob/master/entrypoint.sh#L43

Would you accept to make that step conditional by passing some var?

**Comment by myoung34** [comment]
Totally doable! Id prefer to keep changes backwards compatible at the sake of a `--no-{}` flag|env var if that's fine (usually i don't like no flags vs just flags)

Something like `DISABLE_AUTOMATIC_DEREGISTRATION` (or something similar) ?

**Comment by davidkarlsen** [comment]
> Totally doable! Id prefer to keep changes backwards compatible at the sake of a `--no-{}` flag|env var if that's fine (usually i don't like no flags vs just flags)

that makes perfect sense

> Something like `DISABLE_AUTOMATIC_DEREGISTRATION` (or something similar) ?

sounds perfect

**Comment by myoung34** [comment]
@davidkarlsen If you'd like to review I have a PR up at #101
